# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `path_expander` gem.
# Please instead update this file by running `bin/tapioca gem path_expander`.

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca#manually-requiring-parts-of-a-gem
