# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubydex` gem.
# Please instead update this file by running `bin/tapioca gem rubydex`.


# frozen_string_literal: true
# typed: strict

# source://rubydex//lib/rubydex/version.rb#3
module Rubydex; end

# Raised when `MethodAliasDefinition#target` walks an alias chain that loops back on itself.
#
# source://rubydex//lib/rubydex/errors.rb#7
class Rubydex::AliasCycleError < ::Rubydex::Error; end

class Rubydex::AttrAccessorDefinition < ::Rubydex::Definition; end
class Rubydex::AttrReaderDefinition < ::Rubydex::Definition; end
class Rubydex::AttrWriterDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/declaration.rb#30
class Rubydex::Class < ::Rubydex::Namespace
  include ::Rubydex::Visibility

  # source://rubydex//lib/rubydex.rb#14
  def visibility; end
end

class Rubydex::ClassDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T.nilable(Rubydex::ConstantReference)) }
  def superclass; end
end

class Rubydex::ClassVariable < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

class Rubydex::ClassVariableDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/comment.rb#4
class Rubydex::Comment
  # @return [Comment] a new instance of Comment
  #
  # source://rubydex//lib/rubydex/comment.rb#12
  sig { params(string: String, location: Rubydex::Location).void }
  def initialize(string:, location:); end

  # source://rubydex//lib/rubydex/comment.rb#9
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex/comment.rb#6
  sig { returns(String) }
  def string; end
end

# The configuration of a workspace, parsed from its `rubydex.toml`. It carries both the settings that are global to
# every built-in tool, such as the workspace being analyzed, and the typed settings of each tool's own section (e.g.
# `[graph]`, `[linter]`).
class Rubydex::Config
  # source://rubydex//lib/rubydex.rb#14
  # The linter's settings, read from the `[linter]` section.
  sig { returns(Rubydex::LinterConfig) }
  def linter; end

  # source://rubydex//lib/rubydex.rb#14
  # The configured workspace path, which is usually PWD, except for editors that spawn language servers outside of pwd.
  sig { returns(String) }
  def workspace_path; end

  class << self
    # source://rubydex//lib/rubydex.rb#14
    # Loads the configuration file for `workspace_path/rubydex.toml` if it exists or uses the defaults.
    sig { params(workspace_path: String).returns(Rubydex::Config) }
    def load(workspace_path); end
  end
end

# Raised by `Config.load` when the workspace does not exist, or when its config file cannot be read or is malformed.
# A workspace with no config file at all is not an error.
#
# source://rubydex//lib/rubydex/errors.rb#11
class Rubydex::ConfigError < ::Rubydex::Error; end

# source://rubydex//lib/rubydex/declaration.rb#43
class Rubydex::Constant < ::Rubydex::Declaration
  include ::Rubydex::Visibility

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#14
  def visibility; end
end

# source://rubydex//lib/rubydex/declaration.rb#47
class Rubydex::ConstantAlias < ::Rubydex::Declaration
  include ::Rubydex::Visibility

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T.nilable(Rubydex::Declaration)) }
  def target; end

  # source://rubydex//lib/rubydex.rb#14
  def visibility; end
end

class Rubydex::ConstantAliasDefinition < ::Rubydex::Definition; end
class Rubydex::ConstantDefinition < ::Rubydex::Definition; end

class Rubydex::ConstantReference < ::Rubydex::Reference
  abstract!

  # source://rubydex//lib/rubydex.rb#14
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(Rubydex::Document) }
  def document; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(Rubydex::Location) }
  def location; end

  class << self
    private

    def new(*args); end
  end
end

class Rubydex::ConstantVisibilityDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/declaration.rb#15
class Rubydex::Declaration
  abstract!

  # source://rubydex//lib/rubydex.rb#14
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::Definition]) }
  def definitions; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(String) }
  def name; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(Rubydex::Declaration) }
  def owner; end

  # @abstract
  # @raise [NotImplementedError]
  #
  # source://rubydex//lib/rubydex/declaration.rb#18
  sig { returns(T::Enumerable[Rubydex::Reference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(String) }
  def unqualified_name; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#14
    def new(*_arg0); end
  end
end

class Rubydex::Definition
  abstract!

  # source://rubydex//lib/rubydex.rb#14
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[Rubydex::Comment]) }
  def comments; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T.nilable(Rubydex::Declaration)) }
  def declaration; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Boolean) }
  def deprecated?; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(Rubydex::Document) }
  def document; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[Rubydex::Definition]) }
  def lexical_nesting; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T.nilable(Rubydex::Definition)) }
  def lexical_owner; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(String) }
  def name; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T.nilable(Rubydex::Location)) }
  def name_location; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#14
    def new(*_arg0); end
  end
end

# source://rubydex//lib/rubydex/diagnostic.rb#4
class Rubydex::Diagnostic
  # @return [Diagnostic] a new instance of Diagnostic
  #
  # source://rubydex//lib/rubydex/diagnostic.rb#23
  sig do
    params(
      rule: T.class_of(Rubydex::Rule),
      message: String,
      location: Rubydex::Location,
      related_information: T::Array[Rubydex::RelatedInformation]
    ).void
  end
  def initialize(rule:, message:, location:, related_information: T.unsafe(nil)); end

  # source://rubydex//lib/rubydex/diagnostic.rb#12
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex/diagnostic.rb#9
  sig { returns(String) }
  def message; end

  # source://rubydex//lib/rubydex/diagnostic.rb#15
  sig { returns(T::Array[Rubydex::RelatedInformation]) }
  def related_information; end

  # source://rubydex//lib/rubydex/diagnostic.rb#6
  sig { returns(T.class_of(Rubydex::Rule)) }
  def rule; end
end

# A one based location intended for display purposes. This is what should be used when displaying a location to users,
# like in CLIs
#
# source://rubydex//lib/rubydex/location.rb#86
class Rubydex::DisplayLocation < ::Rubydex::Location
  # Normalize to zero-based for comparison with Location
  #
  #
  # source://rubydex//lib/rubydex/location.rb#108
  sig { returns([String, Integer, Integer, Integer, Integer]) }
  def comparable_values; end

  # Returns itself
  #
  #
  # source://rubydex//lib/rubydex/location.rb#101
  sig { returns(Rubydex::DisplayLocation) }
  def to_display; end

  # source://rubydex//lib/rubydex/location.rb#113
  sig { returns(String) }
  def to_s; end

  class << self
    # @raise [NotImplementedError]
    #
    # source://rubydex//lib/rubydex/location.rb#89
    sig { params(prism_location: Prism::Location, uri: String).returns(T.noreturn) }
    def from_prism(prism_location, uri:); end
  end
end

class Rubydex::Document
  # source://rubydex//lib/rubydex.rb#14
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::Definition]) }
  def definitions; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def method_references; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(String) }
  def uri; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#14
    def new(*_arg0); end
  end
end

# source://rubydex//lib/rubydex/errors.rb#4
class Rubydex::Error < ::StandardError; end

# Represents `extend SomeModule`
#
# source://rubydex//lib/rubydex/mixin.rb#21
class Rubydex::Extend < ::Rubydex::Mixin; end

# source://rubydex//lib/rubydex/failures.rb#4
class Rubydex::Failure
  # @return [Failure] a new instance of Failure
  #
  # source://rubydex//lib/rubydex/failures.rb#9
  sig { params(message: String).void }
  def initialize(message); end

  # source://rubydex//lib/rubydex/failures.rb#6
  sig { returns(String) }
  def message; end
end

class Rubydex::GlobalVariable < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

class Rubydex::GlobalVariableAliasDefinition < ::Rubydex::Definition; end
class Rubydex::GlobalVariableDefinition < ::Rubydex::Definition; end

# The global graph representing all declarations and their relationships for the workspace
#
# Note: this class is partially defined in C to integrate with the Rust backend
#
# source://rubydex//lib/rubydex/graph.rb#7
class Rubydex::Graph
  # source://rubydex//lib/rubydex.rb#14
  sig { params(fully_qualified_name: String).returns(T.nilable(Rubydex::Declaration)) }
  def [](fully_qualified_name); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[Rubydex::Failure]) }
  def check_integrity; end

  # source://rubydex//lib/rubydex.rb#14
  # Returns completion candidates for an expression context. This includes all keywords, constants, methods, instance
  # variables, class variables and global variables reachable from the current lexical scope and self type.
  #
  # The nesting array represents the lexical scope stack. The required `self_receiver` keyword argument overrides the
  # self type independently of the lexical scope (e.g., `"Foo::<Foo>"` for `def Foo.bar`). This distinction is important
  # because constants and class variables are always attached to the lexical scope. Meanwhile, methods and instance
  # variables are attached to the type of `self` and those don't always match. Pass `nil` when the self type is unknown
  sig do
    params(
      nesting: T::Array[String],
      self_receiver: T.nilable(String)
    ).returns(T::Array[T.any(Rubydex::Declaration, Rubydex::Keyword)])
  end
  def complete_expression(nesting, self_receiver:); end

  # source://rubydex//lib/rubydex.rb#14
  # Returns completion candidates inside a method call's argument list (e.g., `foo.bar(|)`). This includes everything
  # that expression completion provides plus keyword argument names of the method being called.
  #
  # See `complete_expression` for the semantics of `nesting` and `self_receiver` (required, may be `nil`).
  sig do
    params(
      name: String,
      nesting: T::Array[String],
      self_receiver: T.nilable(String)
    ).returns(T::Array[T.any(Rubydex::Declaration, Rubydex::Keyword, Rubydex::KeywordParameter)])
  end
  def complete_method_argument(name, nesting, self_receiver:); end

  # source://rubydex//lib/rubydex.rb#14
  # Returns completion candidates after a method call operator (e.g., `foo.`). This includes all methods that exist on
  # the type of the receiver and its ancestors.
  #
  # The required `self_receiver` kwarg is the caller's runtime self type. It's used for visibility checks for `private`
  # and `protected` methods. Pass `nil` for top-level/script scope.
  sig do
    params(
      name: String,
      self_receiver: T.nilable(String)
    ).returns(T::Array[Rubydex::Method])
  end
  def complete_method_call(name, self_receiver:); end

  # source://rubydex//lib/rubydex.rb#14
  # Returns completion candidates after a namespace access operator (e.g., `Foo::`). This includes all constants and
  # singleton methods for the namespace and its ancestors.
  #
  # The required `self_receiver` kwarg is the caller's runtime self type. It's used to filter visibility-restricted
  # singleton methods (e.g., `private_class_method`). Pass `nil` for top-level/script scope.
  sig do
    params(
      name: String,
      self_receiver: T.nilable(String)
    ).returns(T::Array[Rubydex::Declaration])
  end
  def complete_namespace_access(name, self_receiver:); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def constant_references; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::Declaration]) }
  def declarations; end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(uri: String).returns(T.nilable(Rubydex::Document)) }
  def delete_document(uri); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[Rubydex::Diagnostic]) }
  def diagnostics; end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(uri: String).returns(T.nilable(Rubydex::Document)) }
  def document(uri); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::Document]) }
  def documents; end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(encoding: String).void }
  def encoding=(encoding); end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(queries: String).returns(T::Enumerable[Rubydex::Declaration]) }
  def fuzzy_search(*queries); end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(file_paths: T::Array[String]).returns(T::Array[String]) }
  def index_all(file_paths); end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(uri: String, source: String, language_id: String).void }
  def index_source(uri, source, language_id); end

  # Index all files and dependencies of the workspace that exists in `workspace_path`
  #
  # source://rubydex//lib/rubydex/graph.rb#24
  # Index all files and dependencies of the workspace that exists in `workspace_path`
  sig { returns(T::Array[String]) }
  def index_workspace; end

  # source://rubydex//lib/rubydex.rb#14
  # Returns the keyword object for the name, or `nil` if it is not a Ruby keyword
  sig { params(name: String).returns(T.nilable(Rubydex::Keyword)) }
  def keyword(name); end

  # source://rubydex//lib/rubydex.rb#14
  # Loads the configuration in the graph.
  sig { params(config: Rubydex::Config).void }
  def load_config(config); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def method_references; end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(load_paths: T::Array[String]).returns(T::Array[String]) }
  def require_paths(load_paths); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T.self_type) }
  def resolve; end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(name: String, nesting: T::Array[String]).returns(T.nilable(Rubydex::Declaration)) }
  def resolve_constant(name, nesting); end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(require_path: String, load_paths: T::Array[String]).returns(T.nilable(Rubydex::Document)) }
  def resolve_require_path(require_path, load_paths); end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(queries: String).returns(T::Enumerable[Rubydex::Declaration]) }
  def search(*queries); end

  # source://rubydex//lib/rubydex.rb#14
  # The root directory of the workspace being analyzed, which comes from the loaded `Rubydex::Config`
  sig { returns(String) }
  def workspace_path; end

  # Returns all workspace paths that should be indexed
  #
  #
  # source://rubydex//lib/rubydex/graph.rb#31
  sig { returns(T::Array[String]) }
  def workspace_paths; end

  private

  # Searches for the latest installation of the `rbs` gem and adds the paths for the core and stdlib RBS definitions
  # to the list of paths. This method does not require `rbs` to be a part of the bundle. It searches for whatever
  # latest installation of `rbs` exists in the system and fails silently if we can't find one
  #
  #
  # source://rubydex//lib/rubydex/graph.rb#77
  sig { params(paths: T::Array[String]).void }
  def add_core_rbs_definition_paths(paths); end

  # Gathers the paths we have to index for all workspace dependencies
  #
  # source://rubydex//lib/rubydex/graph.rb#53
  sig { params(paths: T::Array[String]).void }
  def add_workspace_dependency_paths(paths); end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(patterns: T::Array[String]).void }
  def exclude_patterns(patterns); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[String]) }
  def excluded_patterns; end

  # source://rubydex//lib/rubydex.rb#14
  def initialize_clone(_arg0); end

  # source://rubydex//lib/rubydex.rb#14
  def initialize_copy(_arg0); end

  class << self
    # Creates a new graph with the loaded configuration. For use cases where the graph must be shared between
    # different tools, do not use this. Create and own a `Config` object instead.
    #
    #
    # source://rubydex//lib/rubydex/graph.rb#15
    # Creates a new graph with the loaded configuration. For use cases where the graph must be shared between
    # different tools, do not use this. Create and own a `Config` object instead.
    sig { params(workspace_path: String).returns(T.attached_class) }
    def configure_for_workspace(workspace_path); end
  end
end

# source://rubydex//lib/rubydex/graph.rb#8
Rubydex::Graph::INDEXABLE_EXTENSIONS = T.let(T.unsafe(nil), Array)

# Represents `include SomeModule`
#
# source://rubydex//lib/rubydex/mixin.rb#15
class Rubydex::Include < ::Rubydex::Mixin; end

class Rubydex::InstanceVariable < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

class Rubydex::InstanceVariableDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/failures.rb#14
class Rubydex::IntegrityFailure < ::Rubydex::Failure; end

# source://rubydex//lib/rubydex/keyword.rb#4
class Rubydex::Keyword
  # @return [Keyword] a new instance of Keyword
  #
  # source://rubydex//lib/rubydex/keyword.rb#12
  sig { params(name: String, documentation: String).void }
  def initialize(name, documentation); end

  # source://rubydex//lib/rubydex/keyword.rb#9
  sig { returns(String) }
  def documentation; end

  # source://rubydex//lib/rubydex/keyword.rb#6
  sig { returns(String) }
  def name; end
end

# source://rubydex//lib/rubydex/keyword_parameter.rb#4
class Rubydex::KeywordParameter
  # @return [KeywordParameter] a new instance of KeywordParameter
  #
  # source://rubydex//lib/rubydex/keyword_parameter.rb#9
  sig { params(name: String).void }
  def initialize(name); end

  # source://rubydex//lib/rubydex/keyword_parameter.rb#6
  sig { returns(String) }
  def name; end
end

module Rubydex::Linter; end

# Base class for semantic lint rules, which collect their diagnostics by walking a resolved graph.
class Rubydex::Linter::CustomRule < Rubydex::Rule
  abstract!

  sig { params(graph: Rubydex::Graph, config: Rubydex::LinterConfig).void }
  def initialize(graph, config:); end

  sig { params(base_name: String).returns(T::Enumerable[Rubydex::Class]) }
  def child_classes(base_name); end

  sig { returns(Rubydex::LinterConfig) }
  def config; end

  sig { params(definition: Rubydex::Definition).returns(Rubydex::Location) }
  def diagnostic_location(definition); end

  sig { returns(T::Array[Rubydex::Diagnostic]) }
  def diagnostics; end

  sig { returns(Rubydex::Graph) }
  def graph; end

  sig { abstract.void }
  def lint; end

  sig { params(namespace: Rubydex::Namespace, method_name: String).returns(Rubydex::Method) }
  def required_method(namespace, method_name); end

  sig { params(name: String).returns(Rubydex::Namespace) }
  def required_namespace(name); end

  sig { returns(String) }
  def rule_name; end

  protected

  sig do
    params(
      message: String,
      location: Rubydex::Location,
      related_information: T::Array[Rubydex::RelatedInformation]
    ).void
  end
  def add_diagnostic(message, location, related_information: []); end
end

module Rubydex::Linter::Helpers; end

module Rubydex::Linter::Helpers::PathHelpers
  extend T::Helpers

  requires_ancestor { Rubydex::Linter::CustomRule }

  sig do
    params(
      definitions: T::Enumerable[Rubydex::Definition],
      excluded_patterns: T::Array[String]
    ).returns(T::Array[Rubydex::Definition])
  end
  def reject_definitions_in_paths(definitions, excluded_patterns); end

  sig do
    params(
      definitions: T::Enumerable[Rubydex::Definition],
      patterns: T::Array[String]
    ).returns(T::Array[Rubydex::Definition])
  end
  def select_definitions_in_paths(definitions, patterns); end

  private

  sig { params(definition: Rubydex::Definition).returns(T.nilable(String)) }
  def path_for_definition(definition); end

  sig { params(path: String, patterns: T::Array[String]).returns(T::Boolean) }
  def path_matches_patterns?(path, patterns); end

  sig { params(path: String).returns(T::Boolean) }
  def test_path?(path); end

  class << self
    sig { params(location: Rubydex::Location, workspace: String).returns(String) }
    def display_path(location, workspace:); end

    sig { params(path: String, patterns: T::Array[String], workspace: String, flags: Integer).returns(T::Boolean) }
    def path_matches_patterns?(path, patterns, workspace:, flags: 0); end
  end

  EXCLUDE_FNMATCH_FLAGS = T.let(T.unsafe(nil), Integer)
  TEST_PATHS = T.let(T.unsafe(nil), T::Array[String])
end

module Rubydex::Linter::Helpers::SourceAccessHelpers
  sig { params(uri: String).returns(Rubydex::Location) }
  def file_location(uri); end

  sig { params(uri: String).returns(String) }
  def path_for_uri(uri); end

  private

  sig { params(location: Rubydex::Location).returns(T.nilable(String)) }
  def source_for_location(location); end
end

class Rubydex::Linter::MissingGraphDependencyError < StandardError
  sig { params(rule_name: String, dependency: String).void }
  def initialize(rule_name, dependency); end
end

class Rubydex::Linter::RuleLoadError < StandardError; end

class Rubydex::Linter::RuleLoader
  class << self
    sig { params(workspace_path: String).void }
    def load(workspace_path); end
  end

  RULE_GLOB = T.let(T.unsafe(nil), String)
end

class Rubydex::Linter::RuleTestCase < Minitest::Test
  sig { params(name: String).void }
  def initialize(name); end

  sig { params(sources: T::Hash[String, String]).void }
  def add_shared_source(sources); end

  sig do
    params(
      args: T.any(String, T::Hash[T.any(String, Symbol), String]),
      rule_builder: T.nilable(T.proc.params(graph: Rubydex::Graph).returns(Rubydex::Linter::CustomRule))
    ).returns(T::Array[Rubydex::Diagnostic])
  end
  def assert_diagnostics(*args, &rule_builder); end

  sig do
    params(
      dependency: String,
      args: T.any(String, T::Hash[T.any(String, Symbol), String]),
      after_excluding: T::Array[String],
      rule_builder: T.nilable(T.proc.params(graph: Rubydex::Graph).returns(Rubydex::Linter::CustomRule))
    ).void
  end
  def assert_handles_missing_required_dependency(dependency, *args, after_excluding: [], &rule_builder); end

  sig do
    params(
      args: T.any(String, T::Hash[T.any(String, Symbol), String]),
      rule_builder: T.nilable(T.proc.params(graph: Rubydex::Graph).returns(Rubydex::Linter::CustomRule))
    ).returns(T::Array[Rubydex::Diagnostic])
  end
  def assert_no_diagnostics(*args, &rule_builder); end

  sig { returns(T::Array[String]) }
  def ignored_diagnostic_files; end

  sig { returns(T.class_of(Rubydex::Linter::CustomRule)) }
  def rule_class; end

  sig { returns(Rubydex::LinterConfig) }
  def rule_config; end

  sig { void }
  def teardown; end

  sig { returns(String) }
  def workspace_path; end

  ANNOTATION_PATTERN = T.let(T.unsafe(nil), Regexp)
  DEFAULT_FILE = T.let(T.unsafe(nil), String)
end

module Rubydex::Linter::Rules; end

class Rubydex::Linter::Rules::RuleStructure < Rubydex::Linter::CustomRule
  include Rubydex::Linter::Helpers::SourceAccessHelpers

  sig { override.void }
  def lint; end

  class << self
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end

  BASE_RULE_NAME = T.let(T.unsafe(nil), String)
  RULE_FILE_PATTERNS = T.let(T.unsafe(nil), T::Array[String])
  RULE_NAMESPACE = T.let(T.unsafe(nil), String)
  TEST_FILE_PATTERNS = T.let(T.unsafe(nil), T::Array[String])
end

class Rubydex::Linter::Runner
  sig do
    params(
      graph: Rubydex::Graph,
      custom_rules: T::Array[T.class_of(Rubydex::Linter::CustomRule)],
      config: Rubydex::LinterConfig
    ).void
  end
  def initialize(graph, custom_rules:, config:); end

  sig { returns(T::Array[T.class_of(Rubydex::Linter::CustomRule)]) }
  def custom_rules; end

  sig { returns(Rubydex::Graph) }
  def graph; end

  sig { returns(T::Array[Rubydex::Diagnostic]) }
  def run; end
end

# The linter's settings, read from the `[linter]` section of the configuration file.
#
# source://rubydex//lib/rubydex/config.rb#5
class Rubydex::LinterConfig
  # @return [LinterConfig] a new instance of LinterConfig
  #
  # source://rubydex//lib/rubydex/config.rb#13
  sig { params(rules: T::Hash[String, Rubydex::RuleConfig]).void }
  def initialize(rules); end

  # source://rubydex//lib/rubydex/config.rb#25
  sig { params(rule_class: T.class_of(Rubydex::Rule)).returns(T::Array[String]) }
  def excludes_for(rule_class); end

  # @return [Boolean]
  #
  # source://rubydex//lib/rubydex/config.rb#19
  sig { params(rule_class: T.class_of(Rubydex::Rule)).returns(T::Boolean) }
  def rule_enabled?(rule_class); end

  # The configured rules, keyed by rule name. Only rules the configuration file mentions appear here, so a rule that
  # was never configured is absent rather than present with its defaults.
  #
  #
  # source://rubydex//lib/rubydex/config.rb#10
  sig { returns(T::Hash[String, Rubydex::RuleConfig]) }
  def rules; end

  # source://rubydex//lib/rubydex/config.rb#30
  sig { params(rule_class: T.class_of(Rubydex::Rule)).returns(T.nilable(T.class_of(Rubydex::Severity::Base))) }
  def severity_for(rule_class); end
end

# A zero based internal location. Intended to be used for tool-to-tool communication, such as a language server
# communicating with an editor.
#
# source://rubydex//lib/rubydex/location.rb#6
class Rubydex::Location
  include ::Comparable

  # @return [Location] a new instance of Location
  #
  # source://rubydex//lib/rubydex/location.rb#31
  sig { params(uri: String, start_line: Integer, end_line: Integer, start_column: Integer, end_column: Integer).void }
  def initialize(uri:, start_line:, end_line:, start_column:, end_column:); end

  # source://rubydex//lib/rubydex/location.rb#54
  sig { params(other: T.untyped).returns(T.nilable(Integer)) }
  def <=>(other); end

  # source://rubydex//lib/rubydex/location.rb#61
  sig { returns([String, Integer, Integer, Integer, Integer]) }
  def comparable_values; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def end_column; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def end_line; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def start_column; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def start_line; end

  # Turns this zero based location into a one based location for display purposes.
  #
  #
  # source://rubydex//lib/rubydex/location.rb#68
  sig { returns(Rubydex::DisplayLocation) }
  def to_display; end

  # @raise [NotFileUriError]
  #
  # source://rubydex//lib/rubydex/location.rb#40
  sig { returns(String) }
  def to_file_path; end

  # source://rubydex//lib/rubydex/location.rb#79
  sig { returns(String) }
  def to_s; end

  # source://rubydex//lib/rubydex/location.rb#12
  sig { returns(String) }
  def uri; end

  class << self
    # source://rubydex//lib/rubydex/location.rb#19
    sig { params(prism_location: Prism::Location, uri: String).returns(Rubydex::Location) }
    def from_prism(prism_location, uri:); end
  end
end

# source://rubydex//lib/rubydex/location.rb#7
class Rubydex::Location::NotFileUriError < ::StandardError; end

# source://rubydex//lib/rubydex/declaration.rb#51
class Rubydex::Method < ::Rubydex::Declaration
  include ::Rubydex::Visibility

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#14
  def visibility; end
end

class Rubydex::MethodAliasDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[Rubydex::Signature]) }
  def signatures; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T.nilable(Rubydex::Method)) }
  def target; end
end

class Rubydex::MethodDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[Rubydex::Signature]) }
  def signatures; end
end

class Rubydex::MethodReference < ::Rubydex::Reference
  # source://rubydex//lib/rubydex.rb#14
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(Rubydex::Document) }
  def document; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(String) }
  def name; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T.nilable(Rubydex::Declaration)) }
  def receiver; end
end

class Rubydex::MethodVisibilityDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/mixin.rb#4
class Rubydex::Mixin
  abstract!

  # @return [Mixin] a new instance of Mixin
  #
  # source://rubydex//lib/rubydex/mixin.rb#9
  sig { params(constant_reference: Rubydex::ConstantReference).void }
  def initialize(constant_reference); end

  # source://rubydex//lib/rubydex/mixin.rb#6
  sig { returns(Rubydex::ConstantReference) }
  def constant_reference; end
end

# source://rubydex//lib/rubydex/declaration.rb#34
class Rubydex::Module < ::Rubydex::Namespace
  include ::Rubydex::Visibility

  # source://rubydex//lib/rubydex.rb#14
  def visibility; end
end

class Rubydex::ModuleDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end
end

# source://rubydex//lib/rubydex/declaration.rb#23
class Rubydex::Namespace < ::Rubydex::Declaration
  abstract!

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::Namespace]) }
  def ancestors; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::Namespace]) }
  def descendants; end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(name: String, only_inherited: T::Boolean).returns(T.nilable(Rubydex::Declaration)) }
  def find_member(name, only_inherited: false); end

  # @return [Boolean]
  #
  # source://rubydex//lib/rubydex/declaration.rb#25
  sig { params(ancestor_names: String).returns(T::Boolean) }
  def has_ancestor?(*ancestor_names); end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(name: String).returns(T.nilable(Rubydex::Declaration)) }
  def member(name); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::Declaration]) }
  def members; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T.nilable(Rubydex::SingletonClass)) }
  def singleton_class; end
end

# Represents `prepend SomeModule`
#
# source://rubydex//lib/rubydex/mixin.rb#18
class Rubydex::Prepend < ::Rubydex::Mixin; end

class Rubydex::Query
  # source://rubydex//lib/rubydex.rb#14
  sig { params(graph: Rubydex::Graph).returns(Rubydex::Query::Result) }
  def run(graph); end

  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { params(query: String).returns(Rubydex::Query) }
    def parse(query); end

    # source://rubydex//lib/rubydex.rb#14
    sig { params(format: T.any(String, Symbol)).returns(String) }
    def schema(format = :table); end
  end
end

# The columns and rows produced by one run of a query. Enumerable over its rows.
class Rubydex::Query::Result
  include ::Enumerable
  include Enumerable
  extend T::Generic

  Elem = type_member { { fixed: T::Hash[String, T.untyped] } }

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[String]) }
  def columns; end

  # source://rubydex//lib/rubydex.rb#14
  sig { override.params(block: T.proc.params(row: T::Hash[String, T.untyped]).void).returns(T.self_type) }
  sig { override.returns(T::Enumerator[T::Hash[String, T.untyped]]) }
  def each(&block); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Boolean) }
  def empty?; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(Integer) }
  def length; end

  # source://rubydex//lib/rubydex.rb#14
  sig { params(format: T.any(String, Symbol)).returns(String) }
  def render(format = :table); end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[T::Hash[String, T.untyped]]) }
  def rows; end

  # source://rubydex//lib/rubydex.rb#14
  sig { returns(Integer) }
  def size; end

  class << self
    # A result only comes from `Query#run`. The C extension undefines `new`, so a call raises.
    sig { returns(T.noreturn) }
    def new; end
  end
end

# Raised when a Cypher query cannot be parsed or cannot run. `Rubydex::Query` raises one of its
# subclasses; rescue this class to catch either.
#
# source://rubydex//lib/rubydex/errors.rb#27
class Rubydex::QueryError < ::Rubydex::Error; end

# Raised by `Query#run` when a parsed query fails while it runs against a graph, for example
# because it names an unknown property or relationship type.
#
# source://rubydex//lib/rubydex/errors.rb#34
class Rubydex::QueryExecutionError < ::Rubydex::QueryError; end

# Raised by `Query.parse` when the query is not valid Cypher.
#
# source://rubydex//lib/rubydex/errors.rb#30
class Rubydex::QuerySyntaxError < ::Rubydex::QueryError; end

# source://rubydex//lib/rubydex/reference.rb#4
class Rubydex::Reference
  abstract!

  # source://rubydex//lib/rubydex.rb#14
  def initialize(_arg0, _arg1); end

  # @raise [NotImplementedError]
  #
  # source://rubydex//lib/rubydex/reference.rb#6
  def location; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#14
    def new(*_arg0); end
  end
end

# source://rubydex//lib/rubydex/related_information.rb#4
class Rubydex::RelatedInformation
  # @return [RelatedInformation] a new instance of RelatedInformation
  #
  # source://rubydex//lib/rubydex/related_information.rb#12
  sig { params(message: String, location: Rubydex::Location).void }
  def initialize(message, location); end

  # source://rubydex//lib/rubydex/related_information.rb#9
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex/related_information.rb#6
  sig { returns(String) }
  def message; end
end

class Rubydex::ResolvedConstantReference < ::Rubydex::ConstantReference
  # source://rubydex//lib/rubydex.rb#14
  sig { returns(Rubydex::Declaration) }
  def declaration; end
end

# The identity of a rule. We have different mechanisms for collecting diagnostics, but they all share the same
# fundamental identity: a unique name and a default severity that may be overridden by the user's configuration.
#
# By keeping this identity concept unified, we are able to treat rules consistently regardless of whether they were
# collected by the graph during the analysis or by the linter afterwards.
#
# @abstract
#
# source://rubydex//lib/rubydex/rule.rb#11
class Rubydex::Rule
  abstract!

  class << self
    abstract!

    # @abstract
    # @raise [NotImplementedError]
    #
    # source://rubydex//lib/rubydex/rule.rb#21
    sig { abstract.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end

    # source://rubydex//lib/rubydex/rule.rb#14
    sig { returns(String) }
    def rule_name; end

    # Returns the resolved severity of the rule based on the given configuration.
    #
    #
    # source://rubydex//lib/rubydex/rule.rb#28
    sig { params(config: Rubydex::LinterConfig).returns(T.class_of(Rubydex::Severity::Base)) }
    def severity(config); end
  end
end

# The settings of a single linter rule, read from a `[linter.rules.RuleName]` table.
#
# source://rubydex//lib/rubydex/config.rb#36
class Rubydex::RuleConfig
  # @return [RuleConfig] a new instance of RuleConfig
  #
  # source://rubydex//lib/rubydex/config.rb#47
  sig do
    params(
      name: String,
      enabled: T::Boolean,
      exclude_patterns: T::Array[String],
      severity: T.nilable(T.class_of(Rubydex::Severity::Base))
    ).void
  end
  def initialize(name, enabled, exclude_patterns = T.unsafe(nil), severity = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://rubydex//lib/rubydex/config.rb#55
  sig { returns(T::Boolean) }
  def enabled?; end

  # source://rubydex//lib/rubydex/config.rb#41
  sig { returns(T::Array[String]) }
  def exclude_patterns; end

  # source://rubydex//lib/rubydex/config.rb#38
  sig { returns(String) }
  def name; end

  # source://rubydex//lib/rubydex/config.rb#44
  sig { returns(T.nilable(T.class_of(Rubydex::Severity::Base))) }
  def severity; end
end

module Rubydex::Rules; end
Rubydex::Rules::ALL = T.let(T.unsafe(nil), T::Array[T.class_of(Rubydex::Rule)])

class Rubydex::Rules::DynamicAncestor < ::Rubydex::Rule
  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end
end

class Rubydex::Rules::DynamicConstantReference < ::Rubydex::Rule
  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end
end

class Rubydex::Rules::DynamicSingletonDefinition < ::Rubydex::Rule
  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end
end

class Rubydex::Rules::InvalidConstantVisibility < ::Rubydex::Rule
  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end
end

class Rubydex::Rules::InvalidMethodVisibility < ::Rubydex::Rule
  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end
end

class Rubydex::Rules::ParseError < ::Rubydex::Rule
  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end
end

class Rubydex::Rules::ParseWarning < ::Rubydex::Rule
  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end
end

class Rubydex::Rules::TopLevelMixinSelf < ::Rubydex::Rule
  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end
end

class Rubydex::Rules::UndefinedConstantVisibilityTarget < ::Rubydex::Rule
  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end
end

class Rubydex::Rules::UndefinedMethodVisibilityTarget < ::Rubydex::Rule
  class << self
    # source://rubydex//lib/rubydex.rb#14
    sig { override.returns(T.class_of(Rubydex::Severity::Base)) }
    def default_severity; end
  end
end

# source://rubydex//lib/rubydex/severity.rb#4
module Rubydex::Severity
  class << self
    # @raise [ArgumentError]
    #
    # source://rubydex//lib/rubydex/severity.rb#62
    sig { params(value: Symbol).returns(T.class_of(Rubydex::Severity::Base)) }
    def from_value(value); end
  end
end

# All severities order based on their importance.
#
# source://rubydex//lib/rubydex/severity.rb#57
Rubydex::Severity::ALL = T.let(T.unsafe(nil), T::Array[T.class_of(Rubydex::Severity::Base)])

# @abstract
#
# source://rubydex//lib/rubydex/severity.rb#6
class Rubydex::Severity::Base
  abstract!

  class << self
    # @abstract
    # @raise [NotImplementedError]
    #
    # source://rubydex//lib/rubydex/severity.rb#10
    sig { returns(Symbol) }
    def value; end
  end
end

# source://rubydex//lib/rubydex/severity.rb#16
class Rubydex::Severity::Error < ::Rubydex::Severity::Base
  class << self
    # source://rubydex//lib/rubydex/severity.rb#20
    def value; end
  end
end

# source://rubydex//lib/rubydex/severity.rb#46
class Rubydex::Severity::Hint < ::Rubydex::Severity::Base
  class << self
    # source://rubydex//lib/rubydex/severity.rb#50
    def value; end
  end
end

# source://rubydex//lib/rubydex/severity.rb#36
class Rubydex::Severity::Information < ::Rubydex::Severity::Base
  class << self
    # source://rubydex//lib/rubydex/severity.rb#40
    def value; end
  end
end

# source://rubydex//lib/rubydex/severity.rb#58
Rubydex::Severity::VALUE_MAP = T.let(T.unsafe(nil), Hash)

# source://rubydex//lib/rubydex/severity.rb#26
class Rubydex::Severity::Warning < ::Rubydex::Severity::Base
  class << self
    # source://rubydex//lib/rubydex/severity.rb#30
    def value; end
  end
end

# source://rubydex//lib/rubydex/signature.rb#4
class Rubydex::Signature
  # @return [Signature] a new instance of Signature
  #
  # source://rubydex//lib/rubydex/signature.rb#33
  sig { params(parameters: T::Array[Rubydex::Signature::Parameter]).void }
  def initialize(parameters); end

  # source://rubydex//lib/rubydex/signature.rb#128
  sig { returns(T.nilable(Rubydex::Signature::BlockParameter)) }
  def block_parameter; end

  # source://rubydex//lib/rubydex/signature.rb#38
  sig do
    returns([
      T::Array[Rubydex::Signature::PositionalParameter],
      T::Array[Rubydex::Signature::OptionalPositionalParameter],
      T.nilable(Rubydex::Signature::RestPositionalParameter),
      T::Array[Rubydex::Signature::PostParameter],
      T::Array[Rubydex::Signature::KeywordParameter],
      T::Array[Rubydex::Signature::OptionalKeywordParameter],
      T.nilable(Rubydex::Signature::RestKeywordParameter),
      T.nilable(Rubydex::Signature::ForwardParameter),
      T.nilable(Rubydex::Signature::BlockParameter),
    ])
  end
  def deconstruct; end

  # source://rubydex//lib/rubydex/signature.rb#80
  sig { params(keys: T.nilable(T::Array[Symbol])).returns(T::Hash[Symbol, T.untyped]) }
  def deconstruct_keys(keys); end

  # source://rubydex//lib/rubydex/signature.rb#125
  sig { returns(T.nilable(Rubydex::Signature::ForwardParameter)) }
  def forward_parameter; end

  # source://rubydex//lib/rubydex/signature.rb#116
  sig { returns(T::Array[Rubydex::Signature::KeywordParameter]) }
  def keyword_parameters; end

  # source://rubydex//lib/rubydex/signature.rb#119
  sig { returns(T::Array[Rubydex::Signature::OptionalKeywordParameter]) }
  def optional_keyword_parameters; end

  # source://rubydex//lib/rubydex/signature.rb#107
  sig { returns(T::Array[Rubydex::Signature::OptionalPositionalParameter]) }
  def optional_positional_parameters; end

  # source://rubydex//lib/rubydex/signature.rb#30
  sig { returns(T::Array[Rubydex::Signature::Parameter]) }
  def parameters; end

  # source://rubydex//lib/rubydex/signature.rb#104
  sig { returns(T::Array[Rubydex::Signature::PositionalParameter]) }
  def positional_parameters; end

  # source://rubydex//lib/rubydex/signature.rb#113
  sig { returns(T::Array[Rubydex::Signature::PostParameter]) }
  def post_parameters; end

  # source://rubydex//lib/rubydex/signature.rb#122
  sig { returns(T.nilable(Rubydex::Signature::RestKeywordParameter)) }
  def rest_keyword_parameter; end

  # source://rubydex//lib/rubydex/signature.rb#110
  sig { returns(T.nilable(Rubydex::Signature::RestPositionalParameter)) }
  def rest_positional_parameter; end
end

# source://rubydex//lib/rubydex/signature.rb#27
class Rubydex::Signature::BlockParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#66
Rubydex::Signature::DECONSTRUCT_KEYS = T.let(T.unsafe(nil), Array)

# source://rubydex//lib/rubydex/signature.rb#26
class Rubydex::Signature::ForwardParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#23
class Rubydex::Signature::KeywordParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#24
class Rubydex::Signature::OptionalKeywordParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#20
class Rubydex::Signature::OptionalPositionalParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#5
class Rubydex::Signature::Parameter
  # @return [Parameter] a new instance of Parameter
  #
  # source://rubydex//lib/rubydex/signature.rb#13
  sig { params(name: Symbol, location: Rubydex::Location).void }
  def initialize(name, location); end

  # source://rubydex//lib/rubydex/signature.rb#10
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex/signature.rb#7
  sig { returns(Symbol) }
  def name; end
end

# source://rubydex//lib/rubydex/signature.rb#19
class Rubydex::Signature::PositionalParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#22
class Rubydex::Signature::PostParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#25
class Rubydex::Signature::RestKeywordParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#21
class Rubydex::Signature::RestPositionalParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/declaration.rb#38
class Rubydex::SingletonClass < ::Rubydex::Namespace
  # source://rubydex//lib/rubydex/declaration.rb#40
  sig { returns(Rubydex::Declaration) }
  def attached_class; end
end

class Rubydex::SingletonClassDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#14
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end
end

# Raised by `Skill.load` when the file cannot be read, is missing frontmatter, has malformed YAML, or lacks the
# required `name` or `description` fields.
# Every failure to produce a Skill is a `SkillError`, so a caller rescues one class instead
# of the union of what `File.read` and Psych happen to raise.
#
# source://rubydex//lib/rubydex/errors.rb#17
class Rubydex::SkillError < ::Rubydex::Error; end

# Raised when a query result names a node that the graph no longer holds, because the graph
# changed after the query ran. Reading the rows would silently turn that column from a
# `Declaration`, `Definition`, or `Document` handle into a plain String, so it raises instead.
# `render`, `columns`, `size`, and `empty?` still work, because they read the executed result set
# and never touch the graph.
#
# The check runs while a row is built, so it covers the rows that a walk has not reached yet. Two
# cases fall outside it:
#
# - A handle that a walk already handed out. Such a handle resolves against the graph on each
#   call, so a later change to the graph can make it stale. Handles from `Graph#[]` share that
#   property. This error says nothing about them.
# - A re-index that keeps the ids. A declaration id comes from the name, so a file indexed again
#   under the same names still resolves, and this error does not fire, even though the
#   definitions and ancestors behind that name may differ.
#
# source://rubydex//lib/rubydex/errors.rb#51
class Rubydex::StaleQueryResultError < ::Rubydex::QueryError; end

class Rubydex::Todo < ::Rubydex::Namespace; end

# Raised by `SkillRegistry.load` when the skill directory doesn't exist.
#
# source://rubydex//lib/rubydex/errors.rb#23
class Rubydex::UnknownSkillDirectoryError < ::Rubydex::SkillError; end

# Raised by `SkillRegistry#fetch` when the library has no skill under the requested id.
#
# source://rubydex//lib/rubydex/errors.rb#20
class Rubydex::UnknownSkillError < ::Rubydex::SkillError; end

class Rubydex::UnresolvedConstantReference < ::Rubydex::ConstantReference
  # source://rubydex//lib/rubydex.rb#14
  sig { returns(String) }
  def name; end
end

# source://rubydex//lib/rubydex/version.rb#4
Rubydex::VERSION = T.let(T.unsafe(nil), String)

# source://rubydex//lib/rubydex/declaration.rb#4
module Rubydex::Visibility
  # @return [Boolean]
  #
  # source://rubydex//lib/rubydex/declaration.rb#9
  def private?; end

  # @return [Boolean]
  #
  # source://rubydex//lib/rubydex/declaration.rb#12
  def protected?; end

  # @return [Boolean]
  #
  # source://rubydex//lib/rubydex/declaration.rb#6
  def public?; end
end
