# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubydex` gem.
# Please instead update this file by running `bin/tapioca gem rubydex`.


# frozen_string_literal: true
# typed: strict

# source://rubydex//lib/rubydex/version.rb#3
module Rubydex; end

# Raised when `MethodAliasDefinition#target` walks an alias chain that loops back on itself.
#
# source://rubydex//lib/rubydex/errors.rb#7
class Rubydex::AliasCycleError < ::Rubydex::Error; end

class Rubydex::AttrAccessorDefinition < ::Rubydex::Definition; end
class Rubydex::AttrReaderDefinition < ::Rubydex::Definition; end
class Rubydex::AttrWriterDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/declaration.rb#30
class Rubydex::Class < ::Rubydex::Namespace
  include ::Rubydex::Visibility

  # source://rubydex//lib/rubydex.rb#11
  def visibility; end
end

class Rubydex::ClassDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::ConstantReference)) }
  def superclass; end
end

class Rubydex::ClassVariable < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

class Rubydex::ClassVariableDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/comment.rb#4
class Rubydex::Comment
  # @return [Comment] a new instance of Comment
  #
  # source://rubydex//lib/rubydex/comment.rb#12
  sig { params(string: String, location: Rubydex::Location).void }
  def initialize(string:, location:); end

  # source://rubydex//lib/rubydex/comment.rb#9
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex/comment.rb#6
  sig { returns(String) }
  def string; end
end

# Raised by `Graph#load_config` when the requested config file does not exist, cannot be read, or is malformed
#
# source://rubydex//lib/rubydex/errors.rb#10
class Rubydex::ConfigError < ::Rubydex::Error; end

# source://rubydex//lib/rubydex/declaration.rb#43
class Rubydex::Constant < ::Rubydex::Declaration
  include ::Rubydex::Visibility

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#11
  def visibility; end
end

# source://rubydex//lib/rubydex/declaration.rb#47
class Rubydex::ConstantAlias < ::Rubydex::Declaration
  include ::Rubydex::Visibility

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::Declaration)) }
  def target; end

  # source://rubydex//lib/rubydex.rb#11
  def visibility; end
end

class Rubydex::ConstantAliasDefinition < ::Rubydex::Definition; end
class Rubydex::ConstantDefinition < ::Rubydex::Definition; end

class Rubydex::ConstantReference < ::Rubydex::Reference
  abstract!

  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Document) }
  def document; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Location) }
  def location; end

  class << self
    def new(*args); end
  end
end

class Rubydex::ConstantVisibilityDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/declaration.rb#15
class Rubydex::Declaration
  abstract!

  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Definition]) }
  def definitions; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def name; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Declaration) }
  def owner; end

  # @abstract
  # @raise [NotImplementedError]
  #
  # source://rubydex//lib/rubydex/declaration.rb#18
  sig { returns(T::Enumerable[Rubydex::Reference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def unqualified_name; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#11
    def new(*_arg0); end
  end
end

class Rubydex::Definition
  abstract!

  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Comment]) }
  def comments; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::Declaration)) }
  def declaration; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Boolean) }
  def deprecated?; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Document) }
  def document; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Definition]) }
  def lexical_nesting; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::Definition)) }
  def lexical_owner; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def name; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::Location)) }
  def name_location; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#11
    def new(*_arg0); end
  end
end

# source://rubydex//lib/rubydex/diagnostic.rb#4
class Rubydex::Diagnostic
  # @return [Diagnostic] a new instance of Diagnostic
  #
  # source://rubydex//lib/rubydex/diagnostic.rb#15
  sig { params(rule: Symbol, message: String, location: Rubydex::Location).void }
  def initialize(rule:, message:, location:); end

  # source://rubydex//lib/rubydex/diagnostic.rb#12
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex/diagnostic.rb#9
  sig { returns(String) }
  def message; end

  # source://rubydex//lib/rubydex/diagnostic.rb#6
  sig { returns(Symbol) }
  def rule; end
end

# A one based location intended for display purposes. This is what should be used when displaying a location to users,
# like in CLIs
#
# source://rubydex//lib/rubydex/location.rb#83
class Rubydex::DisplayLocation < ::Rubydex::Location
  # Normalize to zero-based for comparison with Location
  #
  #
  # source://rubydex//lib/rubydex/location.rb#105
  sig { returns([String, Integer, Integer, Integer, Integer]) }
  def comparable_values; end

  # Returns itself
  #
  #
  # source://rubydex//lib/rubydex/location.rb#98
  sig { returns(Rubydex::DisplayLocation) }
  def to_display; end

  # source://rubydex//lib/rubydex/location.rb#110
  sig { returns(String) }
  def to_s; end

  class << self
    # @raise [NotImplementedError]
    #
    # source://rubydex//lib/rubydex/location.rb#86
    sig { params(prism_location: Prism::Location, uri: String).returns(T.noreturn) }
    def from_prism(prism_location, uri:); end
  end
end

class Rubydex::Document
  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Definition]) }
  def definitions; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def method_references; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def uri; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#11
    def new(*_arg0); end
  end
end

# source://rubydex//lib/rubydex/errors.rb#4
class Rubydex::Error < ::StandardError; end

# Represents `extend SomeModule`
#
# source://rubydex//lib/rubydex/mixin.rb#21
class Rubydex::Extend < ::Rubydex::Mixin; end

# source://rubydex//lib/rubydex/failures.rb#4
class Rubydex::Failure
  # @return [Failure] a new instance of Failure
  #
  # source://rubydex//lib/rubydex/failures.rb#9
  sig { params(message: String).void }
  def initialize(message); end

  # source://rubydex//lib/rubydex/failures.rb#6
  sig { returns(String) }
  def message; end
end

class Rubydex::GlobalVariable < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

class Rubydex::GlobalVariableAliasDefinition < ::Rubydex::Definition; end
class Rubydex::GlobalVariableDefinition < ::Rubydex::Definition; end

# The global graph representing all declarations and their relationships for the workspace
#
# Note: this class is partially defined in C to integrate with the Rust backend
#
# source://rubydex//lib/rubydex/graph.rb#7
class Rubydex::Graph
  # @return [Graph] a new instance of Graph
  #
  # source://rubydex//lib/rubydex/graph.rb#11
  sig { params(workspace_path: T.nilable(String)).void }
  def initialize(workspace_path: T.unsafe(nil)); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(fully_qualified_name: String).returns(T.nilable(Rubydex::Declaration)) }
  def [](fully_qualified_name); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Failure]) }
  def check_integrity; end

  # source://rubydex//lib/rubydex.rb#11
  sig do
    params(
      nesting: T::Array[String],
      self_receiver: T.nilable(String),
    ).returns(T::Array[T.any(Rubydex::Declaration, Rubydex::Keyword)])
  end
  def complete_expression(nesting, self_receiver:); end

  # source://rubydex//lib/rubydex.rb#11
  sig do
    params(
      name: String,
      nesting: T::Array[String],
      self_receiver: T.nilable(String),
    ).returns(T::Array[T.any(Rubydex::Declaration, Rubydex::Keyword, Rubydex::KeywordParameter)])
  end
  def complete_method_argument(name, nesting, self_receiver:); end

  # source://rubydex//lib/rubydex.rb#11
  sig do
    params(
      name: String,
      self_receiver: T.nilable(String),
    ).returns(T::Array[Rubydex::Method])
  end
  def complete_method_call(name, self_receiver:); end

  # source://rubydex//lib/rubydex.rb#11
  sig do
    params(
      name: String,
      self_receiver: T.nilable(String),
    ).returns(T::Array[Rubydex::Declaration])
  end
  def complete_namespace_access(name, self_receiver:); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def constant_references; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Declaration]) }
  def declarations; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(uri: String).returns(T.nilable(Rubydex::Document)) }
  def delete_document(uri); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Diagnostic]) }
  def diagnostics; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(uri: String).returns(T.nilable(Rubydex::Document)) }
  def document(uri); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Document]) }
  def documents; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(encoding: String).void }
  def encoding=(encoding); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(queries: String).returns(T::Enumerable[Rubydex::Declaration]) }
  def fuzzy_search(*queries); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(file_paths: T::Array[String]).returns(T::Array[String]) }
  def index_all(file_paths); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(uri: String, source: String, language_id: String).void }
  def index_source(uri, source, language_id); end

  # Index all files and dependencies of the workspace that exists in `workspace_path`
  #
  # source://rubydex//lib/rubydex/graph.rb#17
  # Index all files and dependencies of the workspace that exists in `workspace_path`
  sig { returns(T::Array[String]) }
  def index_workspace; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(name: String).returns(T.nilable(Rubydex::Keyword)) }
  def keyword(name); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(config_path: T.nilable(String)).void }
  def load_config(config_path = T.unsafe(nil)); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def method_references; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(load_paths: T::Array[String]).returns(T::Array[String]) }
  def require_paths(load_paths); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.self_type) }
  def resolve; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(name: String, nesting: T::Array[String]).returns(T.nilable(Rubydex::Declaration)) }
  def resolve_constant(name, nesting); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(require_path: String, load_paths: T::Array[String]).returns(T.nilable(Rubydex::Document)) }
  def resolve_require_path(require_path, load_paths); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(queries: String).returns(T::Enumerable[Rubydex::Declaration]) }
  def search(*queries); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def workspace_path; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(workspace_path: String).returns(String) }
  def workspace_path=(workspace_path); end

  # Returns all workspace paths that should be indexed
  #
  #
  # source://rubydex//lib/rubydex/graph.rb#24
  sig { returns(T::Array[String]) }
  def workspace_paths; end

  private

  # Searches for the latest installation of the `rbs` gem and adds the paths for the core and stdlib RBS definitions
  # to the list of paths. This method does not require `rbs` to be a part of the bundle. It searches for whatever
  # latest installation of `rbs` exists in the system and fails silently if we can't find one
  #
  #
  # source://rubydex//lib/rubydex/graph.rb#70
  sig { params(paths: T::Array[String]).void }
  def add_core_rbs_definition_paths(paths); end

  # Gathers the paths we have to index for all workspace dependencies
  #
  # source://rubydex//lib/rubydex/graph.rb#46
  sig { params(paths: T::Array[String]).void }
  def add_workspace_dependency_paths(paths); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(patterns: T::Array[String]).void }
  def exclude_patterns(patterns); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[String]) }
  def excluded_patterns; end

  # source://rubydex//lib/rubydex.rb#11
  def initialize_clone(_arg0); end

  # source://rubydex//lib/rubydex.rb#11
  def initialize_copy(_arg0); end
end

# source://rubydex//lib/rubydex/graph.rb#8
Rubydex::Graph::INDEXABLE_EXTENSIONS = T.let(T.unsafe(nil), Array)

# Represents `include SomeModule`
#
# source://rubydex//lib/rubydex/mixin.rb#15
class Rubydex::Include < ::Rubydex::Mixin; end

class Rubydex::InstanceVariable < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

class Rubydex::InstanceVariableDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/failures.rb#14
class Rubydex::IntegrityFailure < ::Rubydex::Failure; end

# source://rubydex//lib/rubydex/keyword.rb#4
class Rubydex::Keyword
  # @return [Keyword] a new instance of Keyword
  #
  # source://rubydex//lib/rubydex/keyword.rb#12
  sig { params(name: String, documentation: String).void }
  def initialize(name, documentation); end

  # source://rubydex//lib/rubydex/keyword.rb#9
  sig { returns(String) }
  def documentation; end

  # source://rubydex//lib/rubydex/keyword.rb#6
  sig { returns(String) }
  def name; end
end

# source://rubydex//lib/rubydex/keyword_parameter.rb#4
class Rubydex::KeywordParameter
  # @return [KeywordParameter] a new instance of KeywordParameter
  #
  # source://rubydex//lib/rubydex/keyword_parameter.rb#9
  sig { params(name: String).void }
  def initialize(name); end

  # source://rubydex//lib/rubydex/keyword_parameter.rb#6
  sig { returns(String) }
  def name; end
end

# A zero based internal location. Intended to be used for tool-to-tool communication, such as a language server
# communicating with an editor.
#
# source://rubydex//lib/rubydex/location.rb#6
class Rubydex::Location
  include ::Comparable

  # @return [Location] a new instance of Location
  #
  # source://rubydex//lib/rubydex/location.rb#31
  sig { params(uri: String, start_line: Integer, end_line: Integer, start_column: Integer, end_column: Integer).void }
  def initialize(uri:, start_line:, end_line:, start_column:, end_column:); end

  # source://rubydex//lib/rubydex/location.rb#51
  sig { params(other: T.untyped).returns(T.nilable(Integer)) }
  def <=>(other); end

  # source://rubydex//lib/rubydex/location.rb#58
  sig { returns([String, Integer, Integer, Integer, Integer]) }
  def comparable_values; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def end_column; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def end_line; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def start_column; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def start_line; end

  # Turns this zero based location into a one based location for display purposes.
  #
  #
  # source://rubydex//lib/rubydex/location.rb#65
  sig { returns(Rubydex::DisplayLocation) }
  def to_display; end

  # @raise [NotFileUriError]
  #
  # source://rubydex//lib/rubydex/location.rb#40
  sig { returns(String) }
  def to_file_path; end

  # source://rubydex//lib/rubydex/location.rb#76
  sig { returns(String) }
  def to_s; end

  # source://rubydex//lib/rubydex/location.rb#12
  sig { returns(String) }
  def uri; end

  class << self
    # source://rubydex//lib/rubydex/location.rb#19
    sig { params(prism_location: Prism::Location, uri: String).returns(Rubydex::Location) }
    def from_prism(prism_location, uri:); end
  end
end

# source://rubydex//lib/rubydex/location.rb#7
class Rubydex::Location::NotFileUriError < ::StandardError; end

# source://rubydex//lib/rubydex/declaration.rb#51
class Rubydex::Method < ::Rubydex::Declaration
  include ::Rubydex::Visibility

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#11
  def visibility; end
end

class Rubydex::MethodAliasDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Signature]) }
  def signatures; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::Method)) }
  def target; end
end

class Rubydex::MethodDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Signature]) }
  def signatures; end
end

class Rubydex::MethodReference < ::Rubydex::Reference
  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Document) }
  def document; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def name; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::Declaration)) }
  def receiver; end
end

class Rubydex::MethodVisibilityDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/mixin.rb#4
class Rubydex::Mixin
  abstract!

  # @return [Mixin] a new instance of Mixin
  #
  # source://rubydex//lib/rubydex/mixin.rb#9
  sig { params(constant_reference: Rubydex::ConstantReference).void }
  def initialize(constant_reference); end

  # source://rubydex//lib/rubydex/mixin.rb#6
  sig { returns(Rubydex::ConstantReference) }
  def constant_reference; end
end

# source://rubydex//lib/rubydex/declaration.rb#34
class Rubydex::Module < ::Rubydex::Namespace
  include ::Rubydex::Visibility

  # source://rubydex//lib/rubydex.rb#11
  def visibility; end
end

class Rubydex::ModuleDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end
end

# source://rubydex//lib/rubydex/declaration.rb#23
class Rubydex::Namespace < ::Rubydex::Declaration
  abstract!

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Namespace]) }
  def ancestors; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Namespace]) }
  def descendants; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(name: String, only_inherited: T::Boolean).returns(T.nilable(Rubydex::Declaration)) }
  def find_member(name, only_inherited: false); end

  # @return [Boolean]
  #
  # source://rubydex//lib/rubydex/declaration.rb#25
  sig { params(ancestor_names: String).returns(T::Boolean) }
  def has_ancestor?(*ancestor_names); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(name: String).returns(T.nilable(Rubydex::Declaration)) }
  def member(name); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Declaration]) }
  def members; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::SingletonClass)) }
  def singleton_class; end
end

# Represents `prepend SomeModule`
#
# source://rubydex//lib/rubydex/mixin.rb#18
class Rubydex::Prepend < ::Rubydex::Mixin; end

class Rubydex::Query
  # source://rubydex//lib/rubydex.rb#11
  sig { params(graph: Rubydex::Graph, format: T.any(String, Symbol)).returns(String) }
  def render(graph, format = T.unsafe(nil)); end

  class << self
    # source://rubydex//lib/rubydex.rb#11
    sig { params(query: String).returns(Rubydex::Query) }
    def parse(query); end

    # source://rubydex//lib/rubydex.rb#11
    sig { params(format: T.any(String, Symbol)).returns(String) }
    def schema(format = T.unsafe(nil)); end
  end
end

# source://rubydex//lib/rubydex/reference.rb#4
class Rubydex::Reference
  abstract!

  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # @raise [NotImplementedError]
  #
  # source://rubydex//lib/rubydex/reference.rb#6
  def location; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#11
    def new(*_arg0); end
  end
end

class Rubydex::ResolvedConstantReference < ::Rubydex::ConstantReference
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Declaration) }
  def declaration; end
end

# source://rubydex//lib/rubydex/signature.rb#4
class Rubydex::Signature
  # @return [Signature] a new instance of Signature
  #
  # source://rubydex//lib/rubydex/signature.rb#33
  sig { params(parameters: T::Array[Rubydex::Signature::Parameter]).void }
  def initialize(parameters); end

  # source://rubydex//lib/rubydex/signature.rb#128
  sig { returns(T.nilable(Rubydex::Signature::BlockParameter)) }
  def block_parameter; end

  # source://rubydex//lib/rubydex/signature.rb#38
  sig do
    returns([
      T::Array[Rubydex::Signature::PositionalParameter],
      T::Array[Rubydex::Signature::OptionalPositionalParameter],
      T.nilable(Rubydex::Signature::RestPositionalParameter),
      T::Array[Rubydex::Signature::PostParameter],
      T::Array[Rubydex::Signature::KeywordParameter],
      T::Array[Rubydex::Signature::OptionalKeywordParameter],
      T.nilable(Rubydex::Signature::RestKeywordParameter),
      T.nilable(Rubydex::Signature::ForwardParameter),
      T.nilable(Rubydex::Signature::BlockParameter),
    ])
  end
  def deconstruct; end

  # source://rubydex//lib/rubydex/signature.rb#80
  sig { params(keys: T.nilable(T::Array[Symbol])).returns(T::Hash[Symbol, T.untyped]) }
  def deconstruct_keys(keys); end

  # source://rubydex//lib/rubydex/signature.rb#125
  sig { returns(T.nilable(Rubydex::Signature::ForwardParameter)) }
  def forward_parameter; end

  # source://rubydex//lib/rubydex/signature.rb#116
  sig { returns(T::Array[Rubydex::Signature::KeywordParameter]) }
  def keyword_parameters; end

  # source://rubydex//lib/rubydex/signature.rb#119
  sig { returns(T::Array[Rubydex::Signature::OptionalKeywordParameter]) }
  def optional_keyword_parameters; end

  # source://rubydex//lib/rubydex/signature.rb#107
  sig { returns(T::Array[Rubydex::Signature::OptionalPositionalParameter]) }
  def optional_positional_parameters; end

  # source://rubydex//lib/rubydex/signature.rb#30
  sig { returns(T::Array[Rubydex::Signature::Parameter]) }
  def parameters; end

  # source://rubydex//lib/rubydex/signature.rb#104
  sig { returns(T::Array[Rubydex::Signature::PositionalParameter]) }
  def positional_parameters; end

  # source://rubydex//lib/rubydex/signature.rb#113
  sig { returns(T::Array[Rubydex::Signature::PostParameter]) }
  def post_parameters; end

  # source://rubydex//lib/rubydex/signature.rb#122
  sig { returns(T.nilable(Rubydex::Signature::RestKeywordParameter)) }
  def rest_keyword_parameter; end

  # source://rubydex//lib/rubydex/signature.rb#110
  sig { returns(T.nilable(Rubydex::Signature::RestPositionalParameter)) }
  def rest_positional_parameter; end
end

# source://rubydex//lib/rubydex/signature.rb#27
class Rubydex::Signature::BlockParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#66
Rubydex::Signature::DECONSTRUCT_KEYS = T.let(T.unsafe(nil), Array)

# source://rubydex//lib/rubydex/signature.rb#26
class Rubydex::Signature::ForwardParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#23
class Rubydex::Signature::KeywordParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#24
class Rubydex::Signature::OptionalKeywordParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#20
class Rubydex::Signature::OptionalPositionalParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#5
class Rubydex::Signature::Parameter
  # @return [Parameter] a new instance of Parameter
  #
  # source://rubydex//lib/rubydex/signature.rb#13
  sig { params(name: Symbol, location: Rubydex::Location).void }
  def initialize(name, location); end

  # source://rubydex//lib/rubydex/signature.rb#10
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex/signature.rb#7
  sig { returns(Symbol) }
  def name; end
end

# source://rubydex//lib/rubydex/signature.rb#19
class Rubydex::Signature::PositionalParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#22
class Rubydex::Signature::PostParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#25
class Rubydex::Signature::RestKeywordParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/signature.rb#21
class Rubydex::Signature::RestPositionalParameter < ::Rubydex::Signature::Parameter; end

# source://rubydex//lib/rubydex/declaration.rb#38
class Rubydex::SingletonClass < ::Rubydex::Namespace
  # source://rubydex//lib/rubydex/declaration.rb#40
  sig { returns(Rubydex::Declaration) }
  def attached_class; end
end

class Rubydex::SingletonClassDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end
end

class Rubydex::Todo < ::Rubydex::Namespace; end

class Rubydex::UnresolvedConstantReference < ::Rubydex::ConstantReference
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def name; end
end

# source://rubydex//lib/rubydex/version.rb#4
Rubydex::VERSION = T.let(T.unsafe(nil), String)

# source://rubydex//lib/rubydex/declaration.rb#4
module Rubydex::Visibility
  # @return [Boolean]
  #
  # source://rubydex//lib/rubydex/declaration.rb#9
  def private?; end

  # @return [Boolean]
  #
  # source://rubydex//lib/rubydex/declaration.rb#12
  def protected?; end

  # @return [Boolean]
  #
  # source://rubydex//lib/rubydex/declaration.rb#6
  def public?; end
end
