# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubydex` gem.
# Please instead update this file by running `bin/tapioca gem rubydex`.


# frozen_string_literal: true
# typed: strict

# source://rubydex//lib/rubydex/version.rb#3
module Rubydex; end

class Rubydex::AttrAccessorDefinition < ::Rubydex::Definition; end
class Rubydex::AttrReaderDefinition < ::Rubydex::Definition; end
class Rubydex::AttrWriterDefinition < ::Rubydex::Definition; end
class Rubydex::Class < ::Rubydex::Namespace; end

class Rubydex::ClassDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::ConstantReference)) }
  def superclass; end
end

class Rubydex::ClassVariable < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

class Rubydex::ClassVariableDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/comment.rb#4
class Rubydex::Comment
  # @return [Comment] a new instance of Comment
  #
  # source://rubydex//lib/rubydex/comment.rb#12
  sig { params(string: String, location: Rubydex::Location).void }
  def initialize(string:, location:); end

  # source://rubydex//lib/rubydex/comment.rb#9
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex/comment.rb#6
  sig { returns(String) }
  def string; end
end

class Rubydex::Constant < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end
end

class Rubydex::ConstantAlias < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end
end

class Rubydex::ConstantAliasDefinition < ::Rubydex::Definition; end
class Rubydex::ConstantDefinition < ::Rubydex::Definition; end

class Rubydex::ConstantReference < ::Rubydex::Reference
  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Location) }
  def location; end

  class << self
    def new(*args); end
  end
end

class Rubydex::ConstantVisibilityDefinition < ::Rubydex::Definition; end

class Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Definition]) }
  def definitions; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def name; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Declaration) }
  def owner; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Reference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def unqualified_name; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#11
    def new(*_arg0); end
  end
end

class Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Comment]) }
  def comments; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Boolean) }
  def deprecated?; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def name; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::Location)) }
  def name_location; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#11
    def new(*_arg0); end
  end
end

# source://rubydex//lib/rubydex/diagnostic.rb#4
class Rubydex::Diagnostic
  # @return [Diagnostic] a new instance of Diagnostic
  #
  # source://rubydex//lib/rubydex/diagnostic.rb#15
  sig { params(rule: Symbol, message: String, location: Rubydex::Location).void }
  def initialize(rule:, message:, location:); end

  # source://rubydex//lib/rubydex/diagnostic.rb#12
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex/diagnostic.rb#9
  sig { returns(String) }
  def message; end

  # source://rubydex//lib/rubydex/diagnostic.rb#6
  sig { returns(Symbol) }
  def rule; end
end

# A one based location intended for display purposes. This is what should be used when displaying a location to users,
# like in CLIs
#
# source://rubydex//lib/rubydex/location.rb#70
class Rubydex::DisplayLocation < ::Rubydex::Location
  # Normalize to zero-based for comparison with Location
  #
  #
  # source://rubydex//lib/rubydex/location.rb#81
  sig { returns([String, Integer, Integer, Integer, Integer]) }
  def comparable_values; end

  # Returns itself
  #
  #
  # source://rubydex//lib/rubydex/location.rb#74
  sig { returns(Rubydex::DisplayLocation) }
  def to_display; end

  # source://rubydex//lib/rubydex/location.rb#86
  sig { returns(String) }
  def to_s; end
end

class Rubydex::Document
  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Definition]) }
  def definitions; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def uri; end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#11
    def new(*_arg0); end
  end
end

class Rubydex::Error < StandardError; end

# Represents `extend SomeModule`
#
# source://rubydex//lib/rubydex/mixin.rb#21
class Rubydex::Extend < ::Rubydex::Mixin; end

# source://rubydex//lib/rubydex/failures.rb#4
class Rubydex::Failure
  # @return [Failure] a new instance of Failure
  #
  # source://rubydex//lib/rubydex/failures.rb#9
  sig { params(message: String).void }
  def initialize(message); end

  # source://rubydex//lib/rubydex/failures.rb#6
  sig { returns(String) }
  def message; end
end

class Rubydex::GlobalVariable < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

class Rubydex::GlobalVariableAliasDefinition < ::Rubydex::Definition; end
class Rubydex::GlobalVariableDefinition < ::Rubydex::Definition; end

# The global graph representing all declarations and their relationships for the workspace
#
# Note: this class is partially defined in C to integrate with the Rust backend
#
# source://rubydex//lib/rubydex/graph.rb#7
class Rubydex::Graph
  # @return [Graph] a new instance of Graph
  #
  # source://rubydex//lib/rubydex/graph.rb#24
  sig { params(workspace_path: T.nilable(String)).void }
  def initialize(workspace_path: T.unsafe(nil)); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(fully_qualified_name: String).returns(T.nilable(Rubydex::Declaration)) }
  def [](fully_qualified_name); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Failure]) }
  def check_integrity; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(nesting: T::Array[String]).returns(T::Array[T.any(Rubydex::Declaration, Rubydex::Keyword)]) }
  def complete_expression(nesting); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(name: String, nesting: T::Array[String]).returns(T::Array[T.any(Rubydex::Declaration, Rubydex::Keyword, Rubydex::KeywordParameter)]) }
  def complete_method_argument(name, nesting); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(name: String).returns(T::Array[Rubydex::Method]) }
  def complete_method_call(name); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(name: String).returns(T::Array[Rubydex::Declaration]) }
  def complete_namespace_access(name); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def constant_references; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Declaration]) }
  def declarations; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(uri: String).returns(T.nilable(Rubydex::Document)) }
  def delete_document(uri); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Diagnostic]) }
  def diagnostics; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Document]) }
  def documents; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(encoding: String).void }
  def encoding=(encoding); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(query: String).returns(T::Enumerable[Rubydex::Declaration]) }
  def fuzzy_search(query); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(file_paths: T::Array[String]).returns(T::Array[String]) }
  def index_all(file_paths); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(uri: String, source: String, language_id: String).void }
  def index_source(uri, source, language_id); end

  # Index all files and dependencies of the workspace that exists in `@workspace_path`
  #
  # source://rubydex//lib/rubydex/graph.rb#32
  # Index all files and dependencies of the workspace that exists in `@workspace_path`
  sig { returns(T::Array[String]) }
  def index_workspace; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def method_references; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(load_paths: T::Array[String]).returns(T::Array[String]) }
  def require_paths(load_paths); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.self_type) }
  def resolve; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(name: String, nesting: T::Array[String]).returns(T.nilable(Rubydex::Declaration)) }
  def resolve_constant(name, nesting); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(require_path: String, load_paths: T::Array[String]).returns(T.nilable(Rubydex::Document)) }
  def resolve_require_path(require_path, load_paths); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(query: String).returns(T::Enumerable[Rubydex::Declaration]) }
  def search(query); end

  # source://rubydex//lib/rubydex/graph.rb#21
  sig { returns(String) }
  def workspace_path; end

  # source://rubydex//lib/rubydex/graph.rb#21
  sig { params(workspace_path: String).returns(String) }
  def workspace_path=(workspace_path); end

  # Returns all workspace paths that should be indexed, excluding directories that we don't need to descend into such
  # as `.git`, `node_modules`. Also includes any top level Ruby files
  #
  #
  # source://rubydex//lib/rubydex/graph.rb#40
  sig { returns(T::Array[String]) }
  def workspace_paths; end

  private

  # Searches for the latest installation of the `rbs` gem and adds the paths for the core and stdlib RBS definitions
  # to the list of paths. This method does not require `rbs` to be a part of the bundle. It searches for whatever
  # latest installation of `rbs` exists in the system and fails silently if we can't find one
  #
  #
  # source://rubydex//lib/rubydex/graph.rb#87
  sig { params(paths: T::Array[String]).void }
  def add_core_rbs_definition_paths(paths); end

  # Gathers the paths we have to index for all workspace dependencies
  #
  # source://rubydex//lib/rubydex/graph.rb#63
  sig { params(paths: T::Array[String]).void }
  def add_workspace_dependency_paths(paths); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(paths: T::Array[String]).void }
  def exclude_paths(paths); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[String]) }
  def excluded_paths; end
end

# source://rubydex//lib/rubydex/graph.rb#8
Rubydex::Graph::IGNORED_DIRECTORIES = T.let(T.unsafe(nil), Array)

# Represents `include SomeModule`
#
# source://rubydex//lib/rubydex/mixin.rb#15
class Rubydex::Include < ::Rubydex::Mixin; end

class Rubydex::InstanceVariable < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[T.untyped]) }
  def references; end
end

class Rubydex::InstanceVariableDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/failures.rb#14
class Rubydex::IntegrityFailure < ::Rubydex::Failure; end

# source://rubydex//lib/rubydex/keyword.rb#4
class Rubydex::Keyword
  # @return [Keyword] a new instance of Keyword
  #
  # source://rubydex//lib/rubydex/keyword.rb#12
  sig { params(name: String, documentation: String).void }
  def initialize(name, documentation); end

  # source://rubydex//lib/rubydex/keyword.rb#9
  sig { returns(String) }
  def documentation; end

  # source://rubydex//lib/rubydex/keyword.rb#6
  sig { returns(String) }
  def name; end
end

# source://rubydex//lib/rubydex/keyword_parameter.rb#4
class Rubydex::KeywordParameter
  # @return [KeywordParameter] a new instance of KeywordParameter
  #
  # source://rubydex//lib/rubydex/keyword_parameter.rb#9
  sig { params(name: String).void }
  def initialize(name); end

  # source://rubydex//lib/rubydex/keyword_parameter.rb#6
  sig { returns(String) }
  def name; end
end

# A zero based internal location. Intended to be used for tool-to-tool communication, such as a language server
# communicating with an editor.
#
# source://rubydex//lib/rubydex/location.rb#6
class Rubydex::Location
  include ::Comparable

  # @return [Location] a new instance of Location
  #
  # source://rubydex//lib/rubydex/location.rb#18
  sig { params(uri: String, start_line: Integer, end_line: Integer, start_column: Integer, end_column: Integer).void }
  def initialize(uri:, start_line:, end_line:, start_column:, end_column:); end

  # source://rubydex//lib/rubydex/location.rb#38
  sig { params(other: T.untyped).returns(T.nilable(Integer)) }
  def <=>(other); end

  # source://rubydex//lib/rubydex/location.rb#45
  sig { returns([String, Integer, Integer, Integer, Integer]) }
  def comparable_values; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def end_column; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def end_line; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def start_column; end

  # source://rubydex//lib/rubydex/location.rb#15
  sig { returns(Integer) }
  def start_line; end

  # Turns this zero based location into a one based location for display purposes.
  #
  #
  # source://rubydex//lib/rubydex/location.rb#52
  sig { returns(Rubydex::DisplayLocation) }
  def to_display; end

  # @raise [NotFileUriError]
  #
  # source://rubydex//lib/rubydex/location.rb#27
  sig { returns(String) }
  def to_file_path; end

  # source://rubydex//lib/rubydex/location.rb#63
  sig { returns(String) }
  def to_s; end

  # source://rubydex//lib/rubydex/location.rb#12
  sig { returns(String) }
  def uri; end
end

# source://rubydex//lib/rubydex/location.rb#7
class Rubydex::Location::NotFileUriError < ::StandardError; end

class Rubydex::Method < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def references; end
end

class Rubydex::MethodAliasDefinition < ::Rubydex::Definition; end
class Rubydex::MethodDefinition < ::Rubydex::Definition; end

class Rubydex::MethodReference < ::Rubydex::Reference
  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Location) }
  def location; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def name; end
end

class Rubydex::MethodVisibilityDefinition < ::Rubydex::Definition; end

# source://rubydex//lib/rubydex/mixin.rb#4
class Rubydex::Mixin
  # @return [Mixin] a new instance of Mixin
  #
  # source://rubydex//lib/rubydex/mixin.rb#9
  sig { params(constant_reference: Rubydex::ConstantReference).void }
  def initialize(constant_reference); end

  # source://rubydex//lib/rubydex/mixin.rb#6
  def constant_reference; end
end

class Rubydex::Module < ::Rubydex::Namespace; end

class Rubydex::ModuleDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end
end

class Rubydex::Namespace < ::Rubydex::Declaration
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Namespace]) }
  def ancestors; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Namespace]) }
  def descendants; end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(name: String, only_inherited: T::Boolean).returns(T.nilable(Rubydex::Declaration)) }
  def find_member(name, only_inherited: false); end

  # source://rubydex//lib/rubydex.rb#11
  sig { params(name: String).returns(T.nilable(Rubydex::Declaration)) }
  def member(name); end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::Declaration]) }
  def members; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def references; end

  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T.nilable(Rubydex::SingletonClass)) }
  def singleton_class; end
end

# Represents `prepend SomeModule`
#
# source://rubydex//lib/rubydex/mixin.rb#18
class Rubydex::Prepend < ::Rubydex::Mixin; end

class Rubydex::Reference
  # source://rubydex//lib/rubydex.rb#11
  def initialize(_arg0, _arg1); end

  class << self
    private

    # source://rubydex//lib/rubydex.rb#11
    def new(*_arg0); end
  end
end

class Rubydex::ResolvedConstantReference < ::Rubydex::ConstantReference
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(Rubydex::Declaration) }
  def declaration; end
end

class Rubydex::SingletonClass < ::Rubydex::Namespace; end

class Rubydex::SingletonClassDefinition < ::Rubydex::Definition
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(T::Array[Rubydex::Mixin]) }
  def mixins; end
end

class Rubydex::Todo < ::Rubydex::Namespace; end

class Rubydex::UnresolvedConstantReference < ::Rubydex::ConstantReference
  # source://rubydex//lib/rubydex.rb#11
  sig { returns(String) }
  def name; end
end

# source://rubydex//lib/rubydex/version.rb#4
Rubydex::VERSION = T.let(T.unsafe(nil), String)
