inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
  - "vendor/**/*"
  - "features/**/*"

Naming/FileName:
  Exclude:
  - "lib/ruby-lsp.rb"
