inherit_gem:
  rubocop-shopify: rubocop.yml

require:
 - rubocop-sorbet
 - rubocop-minitest
 - rubocop-rake

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
  - "vendor/**/*"
  - "features/**/*"
  - "test/fixtures/**/*"

Naming/FileName:
  Exclude:
  - "lib/ruby-lsp.rb"

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "**/*.rb"
  Exclude:
    - "**/*.rake"
