inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-sorbet
  - rubocop-md
  - rubocop-minitest
  - rubocop-rake
  - ./lib/rubocop/cop/ruby_lsp/use_language_server_aliases

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Include:
    - "sorbet/rbi/shims/**/*.rbi"
  Exclude:
    - "vendor/**/*"
    - "vscode/**/*"
    - "features/**/*"
    - "test/fixtures/**/*"
    - "test/expectations/**/*"
    - "jekyll/**/*"

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Layout/LineLength:
  AllowedPatterns: ['\A\s*#:']

Minitest/AssertPredicate:
  Enabled: true

Naming/FileName:
  Exclude:
    - "lib/ruby-lsp.rb"

RubyLsp/UseLanguageServerAliases:
  Exclude:
    - "test/**/*.rb"

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "test/**/*.rb"
    - "lib/ruby_indexer/test/**/*.rb"
    - "lib/ruby_indexer/lib/ruby_indexer/prefix_tree.rb"
    - "lib/ruby_lsp/load_sorbet.rb"
    - "lib/ruby_lsp/scripts/compose_bundle.rb"
    - "lib/ruby_lsp/test_unit_test_runner.rb"
  Exclude:
    - "**/*.rake"
    - "lib/**/*.rb"

Sorbet/StrictSigil:
  Enabled: true
  Include:
    - "lib/**/*.rb"
  Exclude:
    - "**/*.rake"
    - "test/**/*.rb"
    - "lib/ruby_indexer/test/**/*.rb"
    - "lib/ruby-lsp.rb"
    - "lib/ruby_indexer/lib/ruby_indexer/prefix_tree.rb"
    - "lib/ruby_lsp/load_sorbet.rb"
    - "lib/ruby_lsp/scripts/compose_bundle.rb"
    - "lib/ruby_lsp/test_helper.rb"
    # runs as part of host app where sorbet-runtime may not be available. Using RBS signatures we can get to
    # `typed: true` but not yet `typed: strict`
    - "lib/ruby_lsp/test_unit_test_runner.rb"

Layout/ClassStructure:
  Enabled: true
  Exclude:
    - "test/**/*"
  ExpectedOrder:
    - module_inclusion
    - constants
    - public_attribute_macros
    - public_class_methods # does not recognize `class << self`
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods
  Categories:
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    module_inclusion:
      - include
      - prepend
      - extend
