name: ruby-lsp

type: ruby

up:
  - submodules
  - ruby
  - bundler
  - node:
      yarn: true
      version: 22.15.1
      packages:
        - vscode

commands:
  server: exe/ruby-lsp
  style: bin/rubocop
  typecheck:
    aliases: ["tc"]
    run: "bundle exec srb tc"
  run_ci:
    run: "bundle exec srb tc &&
      bin/rubocop &&
      bin/test &&
      bundle exec exe/ruby-lsp-check"
  test:
    syntax:
      argument: file
      optional: args...
    run: bin/test

env:
  'RUBY_DEBUG_IRB_CONSOLE': '1'
