name: ruby-lsp

type: ruby

up:
  - ruby
  - bundler
  - node:
      yarn: true
      version: 18.15.0
      packages:
        - vscode

commands:
  docs:
    run: bundle exec rake rdoc
    subcommands:
      check:
        run: bundle exec rake ruby_lsp:check_docs
  server: exe/ruby-lsp
  style: bin/rubocop
  typecheck:
    aliases: ["tc"]
    run: "bundle exec srb tc"
  ci:
    run: "bundle exec rake ruby_lsp:check_docs &&
      bundle exec srb tc &&
      bin/rubocop &&
      bin/test &&
      bundle exec exe/ruby-lsp-check"
  test:
    syntax:
      argument: file
      optional: args...
    run: bin/test
