{
  "result": [
    {
      "name": "a",
      "kind": 8,
      "range": {
        "start": {
          "line": 0,
          "character": 12
        },
        "end": {
          "line": 0,
          "character": 14
        }
      },
      "selectionRange": {
        "start": {
          "line": 0,
          "character": 13
        },
        "end": {
          "line": 0,
          "character": 14
        }
      },
      "children": [

      ]
    },
    {
      "name": "b",
      "kind": 8,
      "range": {
        "start": {
          "line": 1,
          "character": 12
        },
        "end": {
          "line": 1,
          "character": 14
        }
      },
      "selectionRange": {
        "start": {
          "line": 1,
          "character": 13
        },
        "end": {
          "line": 1,
          "character": 14
        }
      },
      "children": [

      ]
    },
    {
      "name": "c",
      "kind": 8,
      "range": {
        "start": {
          "line": 1,
          "character": 16
        },
        "end": {
          "line": 1,
          "character": 18
        }
      },
      "selectionRange": {
        "start": {
          "line": 1,
          "character": 17
        },
        "end": {
          "line": 1,
          "character": 18
        }
      },
      "children": [

      ]
    },
    {
      "name": "d",
      "kind": 8,
      "range": {
        "start": {
          "line": 2,
          "character": 14
        },
        "end": {
          "line": 2,
          "character": 16
        }
      },
      "selectionRange": {
        "start": {
          "line": 2,
          "character": 15
        },
        "end": {
          "line": 2,
          "character": 16
        }
      },
      "children": [

      ]
    }
  ]
}
