{
  "result": [
    {
      "name": "Foo",
      "kind": 5,
      "range": {
        "start": {
          "line": 0,
          "character": 0
        },
        "end": {
          "line": 2,
          "character": 3
        }
      },
      "selectionRange": {
        "start": {
          "line": 0,
          "character": 6
        },
        "end": {
          "line": 0,
          "character": 9
        }
      },
      "children": [
        {
          "name": "Bar",
          "kind": 5,
          "range": {
            "start": {
              "line": 1,
              "character": 2
            },
            "end": {
              "line": 1,
              "character": 16
            }
          },
          "selectionRange": {
            "start": {
              "line": 1,
              "character": 8
            },
            "end": {
              "line": 1,
              "character": 11
            }
          },
          "children": [

          ]
        }
      ]
    }
  ]
}
