[
  {
    "name": "@a",
    "kind": 13,
    "range": {
      "start": {
        "line": 0,
        "character": 0
      },
      "end": {
        "line": 0,
        "character": 2
      }
    },
    "selectionRange": {
      "start": {
        "line": 0,
        "character": 0
      },
      "end": {
        "line": 0,
        "character": 2
      }
    },
    "children": [

    ]
  },
  {
    "name": "@aa",
    "kind": 13,
    "range": {
      "start": {
        "line": 1,
        "character": 0
      },
      "end": {
        "line": 1,
        "character": 3
      }
    },
    "selectionRange": {
      "start": {
        "line": 1,
        "character": 0
      },
      "end": {
        "line": 1,
        "character": 3
      }
    },
    "children": [

    ]
  },
  {
    "name": "Foo",
    "kind": 5,
    "range": {
      "start": {
        "line": 3,
        "character": 0
      },
      "end": {
        "line": 11,
        "character": 3
      }
    },
    "selectionRange": {
      "start": {
        "line": 3,
        "character": 6
      },
      "end": {
        "line": 3,
        "character": 9
      }
    },
    "children": [
      {
        "name": "@b",
        "kind": 13,
        "range": {
          "start": {
            "line": 4,
            "character": 2
          },
          "end": {
            "line": 4,
            "character": 4
          }
        },
        "selectionRange": {
          "start": {
            "line": 4,
            "character": 2
          },
          "end": {
            "line": 4,
            "character": 4
          }
        },
        "children": [

        ]
      },
      {
        "name": "@bb",
        "kind": 13,
        "range": {
          "start": {
            "line": 5,
            "character": 2
          },
          "end": {
            "line": 5,
            "character": 5
          }
        },
        "selectionRange": {
          "start": {
            "line": 5,
            "character": 2
          },
          "end": {
            "line": 5,
            "character": 5
          }
        },
        "children": [

        ]
      },
      {
        "name": "initialize",
        "kind": 9,
        "range": {
          "start": {
            "line": 7,
            "character": 2
          },
          "end": {
            "line": 10,
            "character": 5
          }
        },
        "selectionRange": {
          "start": {
            "line": 7,
            "character": 6
          },
          "end": {
            "line": 7,
            "character": 16
          }
        },
        "children": [
          {
            "name": "@c",
            "kind": 13,
            "range": {
              "start": {
                "line": 8,
                "character": 4
              },
              "end": {
                "line": 8,
                "character": 6
              }
            },
            "selectionRange": {
              "start": {
                "line": 8,
                "character": 4
              },
              "end": {
                "line": 8,
                "character": 6
              }
            },
            "children": [

            ]
          },
          {
            "name": "@cc",
            "kind": 13,
            "range": {
              "start": {
                "line": 9,
                "character": 4
              },
              "end": {
                "line": 9,
                "character": 7
              }
            },
            "selectionRange": {
              "start": {
                "line": 9,
                "character": 4
              },
              "end": {
                "line": 9,
                "character": 7
              }
            },
            "children": [

            ]
          }
        ]
      }
    ]
  }
]