[
  {
    "name": "Foo",
    "kind": 2,
    "range": {
      "start": {
        "line": 0,
        "character": 0
      },
      "end": {
        "line": 6,
        "character": 3
      }
    },
    "selectionRange": {
      "start": {
        "line": 0,
        "character": 7
      },
      "end": {
        "line": 0,
        "character": 10
      }
    },
    "children": [
      {
        "name": "Bar",
        "kind": 5,
        "range": {
          "start": {
            "line": 1,
            "character": 2
          },
          "end": {
            "line": 2,
            "character": 5
          }
        },
        "selectionRange": {
          "start": {
            "line": 1,
            "character": 8
          },
          "end": {
            "line": 1,
            "character": 11
          }
        },
        "children": [

        ]
      },
      {
        "name": "Baz",
        "kind": 2,
        "range": {
          "start": {
            "line": 4,
            "character": 2
          },
          "end": {
            "line": 5,
            "character": 5
          }
        },
        "selectionRange": {
          "start": {
            "line": 4,
            "character": 9
          },
          "end": {
            "line": 4,
            "character": 12
          }
        },
        "children": [

        ]
      }
    ]
  }
]
