[
    {
        "name": "Foo",
        "kind": 2,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 1,
                "character": 3
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 7
            },
            "end": {
                "line": 0,
                "character": 10
            }
        },
        "children": []
    },
    {
        "name": "Foo::Bar",
        "kind": 2,
        "range": {
            "start": {
                "line": 3,
                "character": 0
            },
            "end": {
                "line": 4,
                "character": 3
            }
        },
        "selectionRange": {
            "start": {
                "line": 3,
                "character": 7
            },
            "end": {
                "line": 3,
                "character": 15
            }
        },
        "children": []
    },
    {
        "name": "Foo::Bar::Baz",
        "kind": 5,
        "range": {
            "start": {
                "line": 6,
                "character": 0
            },
            "end": {
                "line": 7,
                "character": 3
            }
        },
        "selectionRange": {
            "start": {
                "line": 6,
                "character": 6
            },
            "end": {
                "line": 6,
                "character": 19
            }
        },
        "children": []
    }
]
