{
  "result": [
    {
      "range": {
        "start": {
          "line": 1,
          "character": 2
        },
        "end": {
          "line": 1,
          "character": 10
        }
      },
      "target": "https://api.rubyonrails.org/vRAILTIES_VERSION/classes/ActiveJob/QueueName/ClassMethods.html#method-i-queue_as",
      "tooltip": "Browse the Rails documentation for: ActiveJob::QueueName::ClassMethods#queue_as"
    }
  ],
  "params": [

  ]
}
