---
name: Ruby LSP bug (VS Code)
description: File a bug report about the Ruby LSP with VS Code
labels:
  - bug
  - vscode
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report! Please answer the following questions to help us understand the issue.

        ### Before submitting

        Please follow the instructions on
        [troubleshooting](https://shopify.github.io/ruby-lsp/troubleshooting.html) and make sure you
        are:
        1. On the latest version of the Ruby LSP VS Code extension
        2. On the latest version of the Ruby LSP server gem
        3. On the latest version of VS Code

        ### When submitting

        Please run the `Collect Ruby LSP Information for Issue Reporting` command through VS Code's command
        palette and paste the result below.

  - type: textarea
    attributes:
      label: Description
      description: Reproduction steps
      value: |
        ### Ruby LSP Information

        <!-- Please run `Collect Ruby LSP Information for Issue Reporting` from VS Code's command palette and paste the result here -->

        ### Reproduction steps

        <!-- Suggested structure -->
        1. Start the Ruby LSP using a certain editor
        2. Open a Ruby file
        3. Do something
        4. See unexpected behavior

        **Code snippet or error message**
        ```ruby
        ```
    validations:
      required: true
