---
name: Ruby LSP bug (non-VS Code editors)
description: File a bug report about the Ruby LSP with non-VS Code editors
labels:
  - bug
  - non-vscode
  - help-wanted
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report!
        Please note that the maintainers only have bandwidth to prioritize VS Code support and lean on the community to assist with supporting other editors.
        If you are using a non-VS Code editor, please follow these steps **before submitting a bug report**:

        1. Follow the instructions on [troubleshooting](https://shopify.github.io/ruby-lsp/troubleshooting.html)
        2. Check if the editor and LSP plugin you use are up to date, and if they support the latest [Language Server Protocol Specification](https://microsoft.github.io/language-server-protocol).
        3. Seek help in the [Ruby DX Slack](https://join.slack.com/t/ruby-dx/shared_invite/zt-2c8zjlir6-uUDJl8oIwcen_FS_aA~b6Q).
        4. Seek help in the related editor/plugin's issue tracker.

        Describing prior discussions and troubleshooting steps will help us understand the issue and respond more quickly.
  - type: textarea
    attributes:
      label: Description
      description: Reproduction steps
      value: |
        ### Reproduction steps

        <!--
        **IMPORTANT NOTE**
        Please provide as much detail about your development setup as possible. Often issues with the Ruby LSP are
        specific to a combination of operating system, Ruby version, Ruby version manager, the editor being used and
        project setup. The easier it is to reproduce the problem, the quicker it will likely take to fix it.
        -->

        <!-- Suggested structure -->
        1. Start the Ruby LSP using a certain editor
        2. Open a Ruby file
        3. Do something
        4. See unexpected behavior

        **Code snippet or error message**
        ```ruby
        ```
    validations:
      required: true
