---
name: Ruby LSP bug (VS Code)
description: File a bug report about the Ruby LSP with VS Code
labels:
  - bug
  - vscode
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report! Please answer the following questions to help us understand the issue.

        ### Before submitting

        Please follow the instructions on
        [troubleshooting](https://github.com/Shopify/ruby-lsp/blob/main/TROUBLESHOOTING.md) and make sure you
        are:
        1. On the latest version of the Ruby LSP VS Code extension
        2. On the latest version of the Ruby LSP server gem
        3. On the latest version of VS Code
  - type: textarea
    attributes:
      label: Description
      description: Reproduction steps
      value: |
        ### Reproduction steps

        <!--
        **IMPORTANT NOTE**
        Please provide as much detail about your development setup as possible. Often issues with the Ruby LSP are
        specific to a combination of operating system, Ruby version, Ruby version manager, the editor being used and
        project setup. The easier it is to reproduce the problem, the quicker it will likely take to fix it.
        -->

        <!-- Suggested structure -->
        1. Start the Ruby LSP using a certain editor
        2. Open a Ruby file
        3. Do something
        4. See unexpected behavior

        **Code snippet or error message**
        ```ruby
        ```
    validations:
      required: true
