{
  "result":[
    {
      "position":{
        "line":3,
        "character":8
      },
      "label":"StandardError",
      "tooltip":"StandardError is implied in a bare rescue",
      "paddingLeft":true
    },
    {
      "position":{
        "line":6,
        "character":10
      },
      "label":"StandardError",
      "tooltip":"StandardError is implied in a bare rescue",
      "paddingLeft":true
    }
  ]
}
