{
  "result": {
    "contents": {
      "kind": "markdown",
      "value": "[Rails Document: `AbstractController::Callbacks::ClassMethods#before_action`](https://api.rubyonrails.org/vRAILTIES_VERSION/classes/AbstractController/Callbacks/ClassMethods.html#method-i-before_action)"
    },
    "range": {
      "start": {
        "line": 1,
        "character": 2
      },
      "end": {
        "line": 1,
        "character": 15
      }
    }
  },
  "params": [
    {
      "line": 1,
      "character": 3
    }
  ]
}
