{
  "result": {
    "contents": {
      "kind": "markdown",
      "value": "[Rails Document: `ActionDispatch::Routing::Mapper::Resources#root`](https://api.rubyonrails.org/vRAILTIES_VERSION/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-root)"
    },
    "range": {
      "start": {
        "line": 1,
        "character": 2
      },
      "end": {
        "line": 1,
        "character": 6
      }
    }
  },
  "params": [
    {
      "line": 1,
      "character": 3
    }
  ]
}
