{
  "result": [
    {
      "delta_line": 0,
      "delta_start_char": 4,
      "length": 3,
      "token_type": 1,
      "token_modifiers": 1
    },
    {
      "delta_line": 0,
      "delta_start_char": 21,
      "length": 1,
      "token_type": 0,
      "token_modifiers": 0
    },
    {
      "delta_line": 0,
      "delta_start_char": 8,
      "length": 1,
      "token_type": 0,
      "token_modifiers": 0
    },
    {
      "delta_line": 1,
      "delta_start_char": 7,
      "length": 1,
      "token_type": 0,
      "token_modifiers": 0
    },
    {
      "delta_line": 0,
      "delta_start_char": 3,
      "length": 1,
      "token_type": 0,
      "token_modifiers": 0
    },
    {
      "delta_line": 0,
      "delta_start_char": 3,
      "length": 1,
      "token_type": 0,
      "token_modifiers": 0
    },
    {
      "delta_line": 0,
      "delta_start_char": 3,
      "length": 1,
      "token_type": 0,
      "token_modifiers": 0
    },
    {
      "delta_line": 0,
      "delta_start_char": 3,
      "length": 1,
      "token_type": 0,
      "token_modifiers": 0
    },
    {
      "delta_line": 0,
      "delta_start_char": 3,
      "length": 1,
      "token_type": 0,
      "token_modifiers": 0
    },
    {
      "delta_line": 0,
      "delta_start_char": 3,
      "length": 3,
      "token_type": 0,
      "token_modifiers": 0
    }
  ]
}
