{
  "result": [
{
      "delta_line": 0,
      "delta_start_char": 0,
      "length": 3,
      "token_type": 8,
      "token_modifiers": 0
    },
    {
      "delta_line": 2,
      "delta_start_char": 3,
      "length": 4,
      "token_type": 13,
      "token_modifiers": 0
    },
    {
      "delta_line": 0,
      "delta_start_char": 9,
      "length": 3,
      "token_type": 7,
      "token_modifiers": 0
    },
    {
      "delta_line": 1,
      "delta_start_char": 7,
      "length": 3,
      "token_type": 7,
      "token_modifiers": 0
    },
    {
      "delta_line": 3,
      "delta_start_char": 5,
      "length": 3,
      "token_type": 8,
      "token_modifiers": 0
    }
  ]
}
