{
  "result": [
    {
      "delta_line": 5,
      "delta_start_char": 6,
      "length": 3,
      "token_type": 2,
      "token_modifiers": 0
    },
    {
      "delta_line": 1,
      "delta_start_char": 10,
      "length": 3,
      "token_type": 2,
      "token_modifiers": 0
    },
    {
      "delta_line": 2,
      "delta_start_char": 2,
      "length": 6,
      "token_type": 2,
      "token_modifiers": 0
    },
    {
      "delta_line": 0,
      "delta_start_char": 14,
      "length": 3,
      "token_type": 2,
      "token_modifiers": 0
    },
    {
      "delta_line": 1,
      "delta_start_char": 2,
      "length": 6,
      "token_type": 2,
      "token_modifiers": 0
    },
    {
      "delta_line": 0,
      "delta_start_char": 15,
      "length": 3,
      "token_type": 2,
      "token_modifiers": 0
    },
    {
      "delta_line": 3,
      "delta_start_char": 6,
      "length": 3,
      "token_type": 1,
      "token_modifiers": 1
    },
    {
      "delta_line": 1,
      "delta_start_char": 4,
      "length": 3,
      "token_type": 2,
      "token_modifiers": 0
    },
    {
      "delta_line": 1,
      "delta_start_char": 4,
      "length": 11,
      "token_type": 1,
      "token_modifiers": 0
    }
  ]
}
