{
    "params": [
        {
            "line": 2,
            "character": 4
        }
    ],
    "result": [
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 4
                },
                "end": {
                    "line": 2,
                    "character": 8
                }
            },
            "parent": {
                "range": {
                    "start": {
                        "line": 2,
                        "character": 4
                    },
                    "end": {
                        "line": 2,
                        "character": 17
                    }
                },
                "parent": {
                    "range": {
                        "start": {
                            "line": 1,
                            "character": 2
                        },
                        "end": {
                            "line": 3,
                            "character": 5
                        }
                    },
                    "parent": {
                        "range": {
                            "start": {
                                "line": 0,
                                "character": 0
                            },
                            "end": {
                                "line": 4,
                                "character": 3
                            }
                        }
                    }
                }
            }
        }
    ]
}
