{
    "params": [
        {
            "line": 1,
            "character": 2
        }
    ],
    "result": [
        {
            "range": {
                "start": {
                    "line": 1,
                    "character": 2
                },
                "end": {
                    "line": 1,
                    "character": 7
                }
            },
            "kind": 3
        },
        {
            "range": {
                "start": {
                    "line": 4,
                    "character": 4
                },
                "end": {
                    "line": 4,
                    "character": 9
                }
            },
            "kind": 2
        }
    ]
}
