{
  "params": [
    {
      "line": 2,
      "character": 5
    }
  ],
  "result": [
    {
      "range": {
        "start": {
          "line": 2,
          "character": 4
        },
        "end": {
          "line": 2,
          "character": 8
        }
      },
      "kind": 3
    },
    {
      "range": {
        "start": {
          "line": 6,
          "character": 4
        },
        "end": {
          "line": 6,
          "character": 8
        }
      },
      "kind": 2
    }
  ]
}
