{
    "params": [
        {
            "line": 0,
            "character": 2
        }
    ],
    "result": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 3
                }
            },
            "kind": 3
        },
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 2,
                    "character": 3
                }
            },
            "kind": 2
        },
        {
            "range": {
                "start": {
                    "line": 5,
                    "character": 2
                },
                "end": {
                    "line": 5,
                    "character": 5
                }
            },
            "kind": 2
        }
    ]
}
