{
    "params": [
        {
            "line": 0,
            "character": 5
        }
    ],
    "result": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 4
                },
                "end": {
                    "line": 0,
                    "character": 7
                }
            },
            "kind": 3
        }
    ]
}
