name: CI (indexing)

on:
  push:
    paths:
      - 'Gemfile.lock'
      - 'lib/ruby_indexer/**'
  pull_request:
    paths:
      - 'Gemfile.lock'
      - 'lib/ruby_indexer/**'

jobs:
  indexing_sanity_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true

      - name: Index Top 100 Ruby gems
        run: bundle exec rake index:topgems
