name: CI (indexing)

on:
  push:
    paths:
      - 'Gemfile.lock'
      - 'lib/ruby_indexer/**'
  pull_request:
    paths:
      - 'Gemfile.lock'
      - 'lib/ruby_indexer/**'

jobs:
  indexing_sanity_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          bundler-cache: true

      - name: Index Top 100 Ruby gems
        run: bundle exec rake index:topgems
