name: Release VS Code extension

on:
  push:
    tags:
      - vscode-ruby-lsp-v[0-9]+.[0-9]+.[0-9]+
      - vscode-ruby-lsp-v[0-9]+.[0-9]+.[0-9]+-preview

jobs:
  release_extension:
    if: github.repository == 'Shopify/ruby-lsp'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        name: Set up pnpm
        with:
          version: 10.28.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        name: Use Node.js
        with:
          node-version: "22.21"
          cache: "pnpm"
          cache-dependency-path: "vscode/pnpm-lock.yaml"

      - name: Create CHANGELOG.md
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const fs = require("fs");

            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const includePrereleases = "${{ github.ref_name }}".endsWith("-preview");

            const changelog = releases
              .filter((release) => release.tag_name.startsWith("vscode-ruby-lsp") && (includePrereleases || !release.prerelease))
              .map((release) => `${release.body}\n`)
              .join("\n");

            fs.writeFileSync("vscode/CHANGELOG.md", changelog);

      - name: Copy files needed for release
        run: |
          cp CODE_OF_CONDUCT.md vscode/CODE_OF_CONDUCT.md

      - name: 📦 Install dependencies
        working-directory: ./vscode
        run: pnpm install --frozen-lockfile

      # Stable releases
      - name: Publish extension in the marketplace
        if: ${{ !endsWith(github.ref_name, '-preview') }}
        working-directory: ./vscode
        run: |
          pnpm run package
          pnpm exec vsce publish --packagePath vscode-ruby-lsp.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # Prereleases
      - name: Package and publish prerelease extension in the marketplace
        if: ${{ endsWith(github.ref_name, '-preview') }}
        working-directory: ./vscode
        run: |
          pnpm run package_prerelease
          pnpm exec vsce publish --pre-release --packagePath vscode-ruby-lsp.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # Stable releases for OpenVSX
      - name: Publish extension on OpenVSX
        if: ${{ !endsWith(github.ref_name, '-preview') }}
        working-directory: ./vscode
        run: |
          pnpm run package
          pnpm exec ovsx publish vscode-ruby-lsp.vsix -p ${{ secrets.OPENVSX_TOKEN }}

  release_github:
    name: Create GitHub release
    if: github.repository == 'Shopify/ruby-lsp'
    needs: release_extension
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const { data } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const previousRelease = data.find((release) => release.tag_name.startsWith("vscode-ruby-lsp") && release.tag_name !== "${{ github.ref_name }}");

            const commitResponse = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: previousRelease.tag_name,
              head: "${{ github.ref_name }}"
            });
            console.log(`Found ${commitResponse.data.commits.length} commits`);

            const pullRequests = [];

            for (const commit of commitResponse.data.commits) {
              const pullsResponse = await github.request(`GET /repos/shopify/ruby-lsp/commits/${commit.sha}/pulls`);

              pullsResponse.data.forEach((pr) => {
                if (!pullRequests.some((pull) => pull.url === pr.html_url)) {
                  pullRequests.push({
                    title: pr.title,
                    url: pr.html_url,
                    labels: pr.labels.map((label) => label.name),
                    author: pr.user.login
                  });
                }
              });
            }
            console.log(`Found ${pullRequests.length} pull requests`);

            const relevantPulls = pullRequests.filter((pull) => {
              return pull.labels.some((label) => label === "vscode") &&
                !pull.labels.some((label) => label === "dependencies") &&
                !pull.labels.some((label) => label === "chore")
            });

            const breakingChanges = relevantPulls.filter((pull) => pull.labels.some((label) => label === "breaking-change"));
            const bugFixes = relevantPulls.filter((pull) => pull.labels.some((label) => label === "bugfix"));
            const enhancements = relevantPulls.filter((pull) => pull.labels.some((label) => label === "enhancement"));
            const otherChanges = relevantPulls.filter((pull) => !pull.labels.some((label) => ["bugfix", "enhancement", "breaking-change"].includes(label)));

            let content = `# ${{ github.ref_name }}\n`;

            if (breakingChanges.length > 0) {
              content += `## 🚧 Breaking Changes\n\n${breakingChanges.map((pull) => `- ${pull.title} (${pull.url}) by @${pull.author}`).join("\n")}\n\n`;
            }

            if (enhancements.length > 0) {
              content += `## ✨ Enhancements\n\n${enhancements.map((pull) => `- ${pull.title} (${pull.url}) by @${pull.author}`).join("\n")}\n\n`;
            }

            if (bugFixes.length > 0) {
              content += `## 🐛 Bug Fixes\n\n${bugFixes.map((pull) => `- ${pull.title} (${pull.url}) by @${pull.author}`).join("\n")}\n\n`;
            }

            if (otherChanges.length > 0) {
              content += `## 📦 Other Changes\n\n${otherChanges.map((pull) => `- ${pull.title} (${pull.url}) by @${pull.author}`).join("\n")}\n\n`;
            }

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.ref }}",
              name: "${{ github.ref_name }}",
              body: content,
              prerelease: "${{ github.ref_name }}".endsWith("-preview")
            });
