name: Pull Request Labels

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check for Pull Request Labels
        shell: bash
        run: |
          bin/check_labels "$(gh pr view --json labels ${{ github.event.pull_request.number }})"
